"""
Complex MNL from Tim with 13 parameters
"""

import biogeme.database as db
import biogeme.biogeme as bio
from biogeme.expressions import *
import numpy as np
import pandas as pd

class LPMC_Full:

    def __init__(self, data_folder, file='12_13.csv'):
        self.data_folder = data_folder

        self.file = file

        self.biogeme = None

        self.prep_db()

        self.build()

    def prep_db(self):

        pandas = pd.read_csv(self.data_folder + 'LondonTravel/' + self.file)

        self.database = db.Database('LondonTravel', pandas)

        for col in self.database.data.columns:
            exec("self.%s = Variable('%s')" % (col, col))

    def build(self):
        ASC_CYCLING_NCO_DL0 = Beta('ASC_CYCLING', 0, -100, 100, 0, 'ASC_CYCLING')
        ASC_CYCLING_NCO_DL1 = ASC_CYCLING_NCO_DL0  # Beta('ASC_CYCLING_DL1',0,-100,100,0)
        ASC_CYCLING_CO1_DL0 = ASC_CYCLING_NCO_DL0  # Beta('ASC_CYCLING_CO',0,-100,100,0)
        ASC_CYCLING_CO1_DL1 = ASC_CYCLING_NCO_DL0  # Beta('ASC_CYCLING_CO',0,-100,100,0)
        ASC_CYCLING_CO2_DL0 = ASC_CYCLING_NCO_DL0  # Beta('ASC_CYCLING_CO2',0,-100,100,0)
        ASC_CYCLING_CO2_DL1 = ASC_CYCLING_NCO_DL0  # Beta('ASC_CYCLING_CO2',0,-100,100,0)
        ASC_DRIVING_NCO_DL0 = Beta('ASC_DRIVING_DL0', 0, -100, 100, 0, 'ASC_DRIVING_DL0')
        ASC_DRIVING_NCO_DL1 = Beta('ASC_DRIVING_DL1', 0, -100, 100, 0, 'ASC_DRIVING_DL1')
        ASC_DRIVING_CO1_DL0 = ASC_DRIVING_NCO_DL0  # Beta('ASC_DRIVING_CO1',0,-100,100,0)
        ASC_DRIVING_CO1_DL1 = ASC_DRIVING_NCO_DL1  # Beta('ASC_DRIVING_CO1',0,-100,100,0)
        ASC_DRIVING_CO2_DL0 = ASC_DRIVING_NCO_DL0  # Beta('ASC_DRIVING_CO2',0,-100,100,0)
        ASC_DRIVING_CO2_DL1 = ASC_DRIVING_NCO_DL1  # Beta('ASC_DRIVING_CO2',0,-100,100,0)
        ASC_TRANSIT_NCO_DL0 = Beta('ASC_TRANSIT_NCO', 0, -100, 100, 0, 'ASC_TRANSIT_NCO')
        ASC_TRANSIT_NCO_DL1 = ASC_TRANSIT_NCO_DL0  # Beta('ASC_TRANSIT_NCO_DL1',0,-100,100,0)
        ASC_TRANSIT_CO1_DL0 = Beta('ASC_TRANSIT_CO', 0, -100, 100, 0, 'ASC_TRANSIT_CO')
        ASC_TRANSIT_CO1_DL1 = ASC_TRANSIT_CO1_DL0  # Beta('ASC_TRANSIT_CO_DL1',0,-100,100,0)
        ASC_TRANSIT_CO2_DL0 = ASC_TRANSIT_CO1_DL0  # Beta('ASC_TRANSIT_CO2',0,-100,100,0)
        ASC_TRANSIT_CO2_DL1 = ASC_TRANSIT_CO1_DL1  # Beta('ASC_TRANSIT_CO2',0,-100,100,0)
        ASC_WALKING_NCO_DL0 = Beta('ASC_WALKING_NCO_DL0', 0, -10, 10, 1, 'ASC_WALKING_NCO_DL0')
        ASC_WALKING_NCO_DL1 = Beta('ASC_WALKING_NCO_DL1', 0, -10, 10, 1, 'ASC_WALKING_NCO_DL1')
        ASC_WALKING_CO1_DL0 = Beta('ASC_WALKING_CO1_DL0', 0, -10, 10, 1, 'ASC_WALKING_CO1_DL0')
        ASC_WALKING_CO1_DL1 = Beta('ASC_WALKING_CO1_DL1', 0, -10, 10, 1, 'ASC_WALKING_CO1_DL1')
        ASC_WALKING_CO2_DL0 = Beta('ASC_WALKING_CO2_DL0', 0, -10, 10, 1, 'ASC_WALKING_CO2_DL0')
        ASC_WALKING_CO2_DL1 = Beta('ASC_WALKING_CO2_DL1', 0, -10, 10, 1, 'ASC_WALKING_CO2_DL1')

        # B_AM_PEAK_WALKING_NCO           = Beta('B_AM_PEAK_WALKING_NCO',0,-10,10,1)
        # B_AM_PEAK_CYCLING_NCO           = Beta('B_AM_PEAK_CYCLING_NCO',0,-10,10,0)
        # B_AM_PEAK_TRANSIT_NCO           = Beta('B_AM_PEAK_TRANSIT_NCO',0,-10,10,0)
        # B_AM_PEAK_DRIVING_NCO           = Beta('B_AM_PEAK_DRIVING_NCO',0,-10,10,0)
        # B_AM_PEAK_WALKING_CO1           = Beta('B_AM_PEAK_WALKING_CO1',0,-10,10,1)
        # B_AM_PEAK_CYCLING_CO1           = Beta('B_AM_PEAK_CYCLING_CO1',0,-10,10,0)
        # B_AM_PEAK_TRANSIT_CO1           = Beta('B_AM_PEAK_TRANSIT_CO1',0,-10,10,0)
        # B_AM_PEAK_DRIVING_CO1           = Beta('B_AM_PEAK_DRIVING_CO1',0,-10,10,0)
        # B_AM_PEAK_WALKING_CO2           = Beta('B_AM_PEAK_WALKING_CO2',0,-10,10,1)
        # B_AM_PEAK_CYCLING_CO2           = Beta('B_AM_PEAK_CYCLING_CO2',0,-10,10,0)
        # B_AM_PEAK_TRANSIT_CO2           = Beta('B_AM_PEAK_TRANSIT_CO2',0,-10,10,0)
        # B_AM_PEAK_DRIVING_CO2           = Beta('B_AM_PEAK_DRIVING_CO2',0,-10,10,0)

        B_ADULT_CYCLING_NCO_DL0 = Beta('B_ADULT_CYCLING_NCO2_DL0', 0, -10, 10, 1, 'B_ADULT_CYCLING_NCO2_DL0')
        B_ADULT_CYCLING_NCO_DL1 = Beta('B_ADULT_CYCLING_DL1', 0, -10, 10, 0, 'B_ADULT_CYCLING_DL1')
        B_ADULT_CYCLING_CO1_DL0 = Beta('B_ADULT_CYCLING_CO1_DL0', 0, -10, 10, 1, 'B_ADULT_CYCLING_CO1_DL0')
        B_ADULT_CYCLING_CO1_DL1 = B_ADULT_CYCLING_NCO_DL1  # Beta('B_ADULT_CYCLING_CO1_DL1',0,-10,10,0)
        B_ADULT_CYCLING_CO2_DL0 = B_ADULT_CYCLING_NCO_DL0  # Beta('B_ADULT_CYCLING_CO2',0,-10,10,0)
        B_ADULT_CYCLING_CO2_DL1 = B_ADULT_CYCLING_NCO_DL1  # Beta('B_ADULT_CYCLING_CO2',0,-10,10,0)
        B_ADULT_DRIVING_NCO_DL0 = Beta('B_ADULT_DRIVING_NCO_DL0', 0, -10, 10, 0, 'B_ADULT_DRIVING_NCO_DL0')
        B_ADULT_DRIVING_NCO_DL1 = Beta('B_ADULT_DRIVING_NCO_DL1', 0, -10, 10, 0, 'B_ADULT_DRIVING_NCO_DL1')
        B_ADULT_DRIVING_CO1_DL0 = Beta('B_ADULT_DRIVING_CO1_DL0', 0, -10, 10, 1, 'B_ADULT_DRIVING_CO1_DL0')
        B_ADULT_DRIVING_CO1_DL1 = Beta('B_ADULT_DRIVING_CO1_DL1', 0, -10, 10, 1, 'B_ADULT_DRIVING_CO1_DL1')
        B_ADULT_DRIVING_CO2_DL0 = Beta('B_ADULT_DRIVING_CO2_DL0', 0, -10, 10, 1, 'B_ADULT_DRIVING_CO2_DL0')
        B_ADULT_DRIVING_CO2_DL1 = Beta('B_ADULT_DRIVING_CO2_DL1', 0, -10, 10, 0, 'B_ADULT_DRIVING_CO2_DL1')
        B_ADULT_TRANSIT_NCO_DL0 = Beta('B_ADULT_TRANSIT_NCO', 0, -10, 10, 0, 'B_ADULT_TRANSIT_NCO')
        B_ADULT_TRANSIT_NCO_DL1 = B_ADULT_TRANSIT_NCO_DL0  # Beta('B_ADULT_TRANSIT_NCO_DL1',0,-10,10,0)
        B_ADULT_TRANSIT_CO1_DL0 = Beta('B_ADULT_TRANSIT_CO1_DL0', 0, -10, 10, 1, 'B_ADULT_TRANSIT_CO1_DL0')
        B_ADULT_TRANSIT_CO1_DL1 = Beta('B_ADULT_TRANSIT_CO1_DL1', 0, -10, 10, 0, 'B_ADULT_TRANSIT_CO1_DL1')
        B_ADULT_TRANSIT_CO2_DL0 = Beta('B_ADULT_TRANSIT_CO2_DL0', 0, -10, 10, 1, 'B_ADULT_TRANSIT_CO2_DL0')
        B_ADULT_TRANSIT_CO2_DL1 = Beta('B_ADULT_TRANSIT_CO2_DL1', 0, -10, 10, 1, 'B_ADULT_TRANSIT_CO2_DL1')
        B_ADULT_WALKING_NCO_DL0 = Beta('B_ADULT_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_ADULT_WALKING_NCO_DL0')
        B_ADULT_WALKING_NCO_DL1 = Beta('B_ADULT_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_ADULT_WALKING_NCO_DL1')
        B_ADULT_WALKING_CO1_DL0 = Beta('B_ADULT_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_ADULT_WALKING_CO1_DL0')
        B_ADULT_WALKING_CO1_DL1 = Beta('B_ADULT_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_ADULT_WALKING_CO1_DL1')
        B_ADULT_WALKING_CO2_DL0 = Beta('B_ADULT_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_ADULT_WALKING_CO2_DL0')
        B_ADULT_WALKING_CO2_DL1 = Beta('B_ADULT_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_ADULT_WALKING_CO2_DL1')

        B_CADULT_CYCLING_NCO_DL0 = Beta('B_CADULT_CYCLING_DL0', 0, -10, 10, 0, 'B_CADULT_CYCLING_DL0')
        B_CADULT_CYCLING_NCO_DL1 = Beta('B_CADULT_CYCLING_DL1', 0, -10, 10, 0, 'B_CADULT_CYCLING_DL1')
        B_CADULT_CYCLING_CO1_DL0 = B_CADULT_CYCLING_NCO_DL0  # Beta('B_CADULT_CYCLING_CO1',0,-10,10,0)
        B_CADULT_CYCLING_CO1_DL1 = B_CADULT_CYCLING_NCO_DL1  # Beta('B_CADULT_CYCLING_CO1',0,-10,10,0)
        B_CADULT_CYCLING_CO2_DL0 = B_CADULT_CYCLING_NCO_DL0  # Beta('B_CADULT_CYCLING_CO2',0,-10,10,0)
        B_CADULT_CYCLING_CO2_DL1 = B_CADULT_CYCLING_NCO_DL1  # Beta('B_CADULT_CYCLING_CO2',0,-10,10,0)
        B_CADULT_DRIVING_NCO_DL0 = Beta('B_CADULT_DRIVING_NCO2_DL0', 0, -10, 10, 1, 'B_CADULT_DRIVING_NCO2_DL0')
        B_CADULT_DRIVING_NCO_DL1 = Beta('B_CADULT_DRIVING_NCO2_DL1', 0, -10, 10, 0, 'B_CADULT_DRIVING_NCO2_DL1')
        B_CADULT_DRIVING_CO1_DL0 = Beta('B_CADULT_DRIVING_CO1_DL0', 0, -10, 10, 0, 'B_CADULT_DRIVING_CO1_DL0')
        B_CADULT_DRIVING_CO1_DL1 = Beta('B_CADULT_DRIVING_CO1_DL1', 0, -10, 10, 0, 'B_CADULT_DRIVING_CO1_DL1')
        B_CADULT_DRIVING_CO2_DL0 = B_CADULT_DRIVING_NCO_DL0  # Beta('B_CADULT_DRIVING_CO2',0,-10,10,0)
        B_CADULT_DRIVING_CO2_DL1 = B_CADULT_DRIVING_NCO_DL1  # Beta('B_CADULT_DRIVING_CO2',0,-10,10,0)
        B_CADULT_TRANSIT_NCO_DL0 = Beta('B_CADULT_TRANSIT_NCO_DL0', 0, -10, 10, 0, 'B_CADULT_TRANSIT_NCO_DL0')
        B_CADULT_TRANSIT_NCO_DL1 = Beta('B_CADULT_TRANSIT_NCO_DL1', 0, -10, 10, 0, 'B_CADULT_TRANSIT_NCO_DL1')
        B_CADULT_TRANSIT_CO1_DL0 = Beta('B_CADULT_TRANSIT_CO1_DL0', 0, -10, 10, 1, 'B_CADULT_TRANSIT_CO1_DL0')
        B_CADULT_TRANSIT_CO1_DL1 = Beta('B_CADULT_TRANSIT_CO1_DL1', 0, -10, 10, 1, 'B_CADULT_TRANSIT_CO1_DL1')
        B_CADULT_TRANSIT_CO2_DL0 = Beta('B_CADULT_TRANSIT_CO2_DL0', 0, -10, 10, 1, 'B_CADULT_TRANSIT_CO2_DL0')
        B_CADULT_TRANSIT_CO2_DL1 = Beta('B_CADULT_TRANSIT_CO2_DL1', 0, -10, 10, 1, 'B_CADULT_TRANSIT_CO2_DL1')
        B_CADULT_WALKING_NCO_DL0 = Beta('B_CADULT_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_CADULT_WALKING_NCO_DL0')
        B_CADULT_WALKING_NCO_DL1 = Beta('B_CADULT_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_CADULT_WALKING_NCO_DL1')
        B_CADULT_WALKING_CO1_DL0 = Beta('B_CADULT_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_CADULT_WALKING_CO1_DL0')
        B_CADULT_WALKING_CO1_DL1 = Beta('B_CADULT_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_CADULT_WALKING_CO1_DL1')
        B_CADULT_WALKING_CO2_DL0 = Beta('B_CADULT_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_CADULT_WALKING_CO2_DL0')
        B_CADULT_WALKING_CO2_DL1 = Beta('B_CADULT_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_CADULT_WALKING_CO2_DL1')

        B_CHILD_CYCLING_NCO_DL0 = Beta('B_CHILD_CYCLING_NCO_DL0', 0, -10, 10, 0, 'B_CHILD_CYCLING_NCO_DL0')
        B_CHILD_CYCLING_NCO_DL1 = Beta('B_CHILD_CYCLING_NCO_DL1', 0, -10, 10, 1, 'B_CHILD_CYCLING_NCO_DL1')
        B_CHILD_CYCLING_CO1_DL0 = Beta('B_CHILD_CYCLING_CO1_DL0', 0, -10, 10, 1, 'B_CHILD_CYCLING_CO1_DL0')
        B_CHILD_CYCLING_CO1_DL1 = Beta('B_CHILD_CYCLING_CO1_DL1', 0, -10, 10, 1, 'B_CHILD_CYCLING_CO1_DL1')
        B_CHILD_CYCLING_CO2_DL0 = Beta('B_CHILD_CYCLING_CO2_DL0', 0, -10, 10, 1, 'B_CHILD_CYCLING_CO2_DL0')
        B_CHILD_CYCLING_CO2_DL1 = Beta('B_CHILD_CYCLING_CO2_DL1', 0, -10, 10, 1, 'B_CHILD_CYCLING_CO2_DL1')
        B_CHILD_DRIVING_NCO_DL0 = Beta('B_CHILD_DRIVING_NCO_DL0', 0, -10, 10, 0, 'B_CHILD_DRIVING_NCO_DL0')
        B_CHILD_DRIVING_NCO_DL1 = Beta('B_CHILD_DRIVING_NCO_DL1', 0, -10, 10, 1, 'B_CHILD_DRIVING_NCO_DL1')
        B_CHILD_DRIVING_CO1_DL0 = Beta('B_CHILD_DRIVING_CO1_DL0', 0, -10, 10, 0, 'B_CHILD_DRIVING_CO1_DL0')
        B_CHILD_DRIVING_CO1_DL1 = Beta('B_CHILD_DRIVING_CO1_DL1', 0, -10, 10, 1, 'B_CHILD_DRIVING_CO1_DL1')
        B_CHILD_DRIVING_CO2_DL0 = Beta('B_CHILD_DRIVING_CO2_DL0', 0, -10, 10, 0, 'B_CHILD_DRIVING_CO2_DL0')
        B_CHILD_DRIVING_CO2_DL1 = Beta('B_CHILD_DRIVING_CO2_DL1', 0, -10, 10, 1, 'B_CHILD_DRIVING_CO2_DL1')
        B_CHILD_TRANSIT_NCO_DL0 = Beta('B_CHILD_TRANSIT_NCO_DL0', 0, -10, 10, 1, 'B_CHILD_TRANSIT_NCO_DL0')
        B_CHILD_TRANSIT_NCO_DL1 = Beta('B_CHILD_TRANSIT_NCO_DL1', 0, -10, 10, 1, 'B_CHILD_TRANSIT_NCO_DL1')
        B_CHILD_TRANSIT_CO1_DL0 = Beta('B_CHILD_TRANSIT_CO1_DL0', 0, -10, 10, 0, 'B_CHILD_TRANSIT_CO1_DL0')
        B_CHILD_TRANSIT_CO1_DL1 = Beta('B_CHILD_TRANSIT_CO1_DL1', 0, -10, 10, 1, 'B_CHILD_TRANSIT_CO1_DL1')
        B_CHILD_TRANSIT_CO2_DL0 = Beta('B_CHILD_TRANSIT_CO2_DL0', 0, -10, 10, 1, 'B_CHILD_TRANSIT_CO2_DL0')
        B_CHILD_TRANSIT_CO2_DL1 = Beta('B_CHILD_TRANSIT_CO2_DL1', 0, -10, 10, 1, 'B_CHILD_TRANSIT_CO2_DL1')
        B_CHILD_WALKING_NCO_DL0 = Beta('B_CHILD_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_CHILD_WALKING_NCO_DL0')
        B_CHILD_WALKING_NCO_DL1 = Beta('B_CHILD_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_CHILD_WALKING_NCO_DL1')
        B_CHILD_WALKING_CO1_DL0 = Beta('B_CHILD_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_CHILD_WALKING_CO1_DL0')
        B_CHILD_WALKING_CO1_DL1 = Beta('B_CHILD_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_CHILD_WALKING_CO1_DL1')
        B_CHILD_WALKING_CO2_DL0 = Beta('B_CHILD_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_CHILD_WALKING_CO2_DL0')
        B_CHILD_WALKING_CO2_DL1 = Beta('B_CHILD_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_CHILD_WALKING_CO2_DL1')

        B_COST_CON_NCO_DL0 = Beta('B_COST_CON_NCO_DL0', 0, -10, 10, 1, 'B_COST_CON_NCO_DL0')
        B_COST_CON_NCO_DL1 = Beta('B_COST_CON_NCO_DL1', 0, -10, 10, 1, 'B_COST_CON_NCO_DL1')
        B_COST_CON_CO1_DL0 = Beta('B_COST_CON_CO', 0, -10, 10, 0, 'B_COST_CON_CO')
        B_COST_CON_CO1_DL1 = B_COST_CON_CO1_DL0  # Beta('B_COST_CON_CO_DL1',0,-10,10,0)
        B_COST_CON_CO2_DL0 = B_COST_CON_CO1_DL0  # Beta('B_COST_CON_CO2',0,-10,10,0)
        B_COST_CON_CO2_DL1 = B_COST_CON_CO1_DL1  # Beta('B_COST_CON_CO2',0,-10,10,0)
        B_COST_FUEL_NCO_DL0 = Beta('B_COST_FUEL_NCO_DL0', 0, -10, 10, 1, 'B_COST_FUEL_NCO_DL0')
        B_COST_FUEL_NCO_DL1 = Beta('B_COST_FUEL_NCO_DL1', 0, -10, 10, 0, 'B_COST_FUEL_NCO_DL1')
        B_COST_FUEL_CO1_DL0 = Beta('B_COST_FUEL_CO1_DL0', 0, -10, 10, 1, 'B_COST_FUEL_CO1_DL0')
        B_COST_FUEL_CO1_DL1 = Beta('B_COST_FUEL_CO1_DL1', 0, -10, 10, 1, 'B_COST_FUEL_CO1_DL1')
        B_COST_FUEL_CO2_DL0 = Beta('B_COST_FUEL_CO2_DL0', 0, -10, 10, 1, 'B_COST_FUEL_CO2_DL0')
        B_COST_FUEL_CO2_DL1 = Beta('B_COST_FUEL_CO2_DL1', 0, -10, 10, 0, 'B_COST_FUEL_CO2_DL1')
        B_COST_TRANSIT_NCO_DL0 = Beta('B_COST_TRANSIT_NCO', 0, -10, 10, 0, 'B_COST_TRANSIT_NCO')
        B_COST_TRANSIT_NCO_DL1 = B_COST_TRANSIT_NCO_DL0  # Beta('B_COST_TRANSIT_NCO_DL1',0,-10,10,0)
        B_COST_TRANSIT_CO1_DL0 = Beta('B_COST_TRANSIT_CO1_DL0', 0, -10, 10, 1, 'B_COST_TRANSIT_CO1_DL0')
        B_COST_TRANSIT_CO1_DL1 = Beta('B_COST_TRANSIT_CO1_DL1', 0, -10, 10, 1, 'B_COST_TRANSIT_CO1_DL1')
        B_COST_TRANSIT_CO2_DL0 = Beta('B_COST_TRANSIT_CO2_DL0', 0, -10, 10, 1, 'B_COST_TRANSIT_CO2_DL0')
        B_COST_TRANSIT_CO2_DL1 = Beta('B_COST_TRANSIT_CO2_DL1', 0, -10, 10, 1, 'B_COST_TRANSIT_CO2_DL1')

        B_DISTANCE_CYCLING_NCO_DL0 = Beta('B_DISTANCE_CYCLING_NCO_DL0', 0, -10, 10, 0, 'B_DISTANCE_CYCLING_NCO_DL0')
        B_DISTANCE_CYCLING_NCO_DL1 = Beta('B_DISTANCE_CYCLING_DL1', 0, -10, 10, 0, 'B_DISTANCE_CYCLING_DL1')
        B_DISTANCE_CYCLING_CO1_DL0 = Beta('B_DISTANCE_CYCLING_CO_DL0', 0, -10, 10, 0, 'B_DISTANCE_CYCLING_CO_DL0')
        B_DISTANCE_CYCLING_CO1_DL1 = B_DISTANCE_CYCLING_NCO_DL1  # Beta('B_DISTANCE_CYCLING_CO_DL1',0,-10,10,0)
        B_DISTANCE_CYCLING_CO2_DL0 = B_DISTANCE_CYCLING_CO1_DL0  # Beta('B_DISTANCE_CYCLING_CO2',0,-10,10,0)
        B_DISTANCE_CYCLING_CO2_DL1 = B_DISTANCE_CYCLING_NCO_DL1  # Beta('B_DISTANCE_CYCLING_CO2',0,-10,10,0)
        B_DISTANCE_DRIVING_NCO_DL0 = Beta('B_DISTANCE_DRIVING_NCO_DL0', 0, -10, 10, 0, 'B_DISTANCE_DRIVING_NCO_DL0')
        B_DISTANCE_DRIVING_NCO_DL1 = Beta('B_DISTANCE_DRIVING_DL1', 0, -10, 10, 0, 'B_DISTANCE_DRIVING_DL1')
        B_DISTANCE_DRIVING_CO1_DL0 = Beta('B_DISTANCE_DRIVING_CO_DL0', 0, -10, 10, 0, 'B_DISTANCE_DRIVING_CO_DL0')
        B_DISTANCE_DRIVING_CO1_DL1 = B_DISTANCE_DRIVING_NCO_DL1  # Beta('B_DISTANCE_DRIVING_CO_DL1',0,-10,10,0)
        B_DISTANCE_DRIVING_CO2_DL0 = B_DISTANCE_DRIVING_CO1_DL0  # Beta('B_DISTANCE_DRIVING_CO2',0,-10,10,0)
        B_DISTANCE_DRIVING_CO2_DL1 = B_DISTANCE_DRIVING_NCO_DL1  # Beta('B_DISTANCE_DRIVING_CO2',0,-10,10,0)
        B_DISTANCE_TRANSIT_NCO_DL0 = Beta('B_DISTANCE_TRANSIT_NCO_DL0', 0, -10, 10, 0, 'B_DISTANCE_TRANSIT_NCO_DL0')
        B_DISTANCE_TRANSIT_NCO_DL1 = Beta('B_DISTANCE_TRANSIT_DL1', 0, -10, 10, 0, 'B_DISTANCE_TRANSIT_DL1')
        B_DISTANCE_TRANSIT_CO1_DL0 = Beta('B_DISTANCE_TRANSIT_CO_DL0', 0, -10, 10, 0, 'B_DISTANCE_TRANSIT_CO_DL0')
        B_DISTANCE_TRANSIT_CO1_DL1 = B_DISTANCE_TRANSIT_NCO_DL1  # Beta('B_DISTANCE_TRANSIT_CO_DL1',0,-10,10,0)
        B_DISTANCE_TRANSIT_CO2_DL0 = B_DISTANCE_TRANSIT_CO1_DL0  # Beta('B_DISTANCE_TRANSIT_CO2',0,-10,10,0)
        B_DISTANCE_TRANSIT_CO2_DL1 = B_DISTANCE_TRANSIT_NCO_DL1  # Beta('B_DISTANCE_TRANSIT_CO2',0,-10,10,0)
        B_DISTANCE_WALKING_NCO_DL0 = Beta('B_DISTANCE_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_DISTANCE_WALKING_NCO_DL0')
        B_DISTANCE_WALKING_NCO_DL1 = Beta('B_DISTANCE_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_DISTANCE_WALKING_NCO_DL1')
        B_DISTANCE_WALKING_CO1_DL0 = Beta('B_DISTANCE_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_DISTANCE_WALKING_CO1_DL0')
        B_DISTANCE_WALKING_CO1_DL1 = Beta('B_DISTANCE_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_DISTANCE_WALKING_CO1_DL1')
        B_DISTANCE_WALKING_CO2_DL0 = Beta('B_DISTANCE_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_DISTANCE_WALKING_CO2_DL0')
        B_DISTANCE_WALKING_CO2_DL1 = Beta('B_DISTANCE_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_DISTANCE_WALKING_CO2_DL1')

        # B_DL_CYCLING_NCO            = Beta('B_DL_CYCLING',0,-10,10,0)
        # B_DL_CYCLING_CO1            = B_DL_CYCLING_NCO #Beta('B_DL_CYCLING_CO1',0,-10,10,0)
        # B_DL_CYCLING_CO2            = B_DL_CYCLING_NCO #Beta('B_DL_CYCLING_CO2',0,-10,10,0)
        # B_DL_DRIVING_NCO            = Beta('B_DL_DRIVING_NCO',0,-10,10,0)
        # B_DL_DRIVING_CO1            = Beta('B_DL_DRIVING_CO',0,-10,10,0)
        # B_DL_DRIVING_CO2            = B_DL_DRIVING_CO1 #Beta('B_DL_DRIVING_CO2',0,-10,10,0)
        # B_DL_TRANSIT_NCO1           = Beta('B_DL_TRANSIT_NCO1',0,-10,10,0)
        # B_DL_TRANSIT_CO1            = B_DL_TRANSIT_NCO1 #Beta('B_DL_TRANSIT_CO1',0,-10,10,0)
        # B_DL_TRANSIT_CO2            = Beta('B_DL_TRANSIT_CO2',0,-10,10,0)
        # B_DL_WALKING_NCO            = Beta('B_DL_WALKING_NCO',0,-10,10,1)
        # B_DL_WALKING_CO1            = Beta('B_DL_WALKING_CO1',0,-10,10,1)
        # B_DL_WALKING_CO2            = Beta('B_DL_WALKING_CO2',0,-10,10,1)

        B_FEMALE_CYCLING_NCO_DL0 = Beta('B_FEMALE_CYCLING', 0, -10, 10, 0, 'B_FEMALE_CYCLING')
        B_FEMALE_CYCLING_NCO_DL1 = B_FEMALE_CYCLING_NCO_DL0  # Beta('B_FEMALE_CYCLING_DL1',0,-10,10,0)
        B_FEMALE_CYCLING_CO1_DL0 = B_FEMALE_CYCLING_NCO_DL0  # Beta('B_FEMALE_CYCLING_CO1',0,-10,10,0)
        B_FEMALE_CYCLING_CO1_DL1 = B_FEMALE_CYCLING_NCO_DL0  # Beta('B_FEMALE_CYCLING_CO1',0,-10,10,0)
        B_FEMALE_CYCLING_CO2_DL0 = B_FEMALE_CYCLING_NCO_DL0  # Beta('B_FEMALE_CYCLING_CO2',0,-10,10,0)
        B_FEMALE_CYCLING_CO2_DL1 = B_FEMALE_CYCLING_NCO_DL0  # Beta('B_FEMALE_CYCLING_CO2',0,-10,10,0)
        B_FEMALE_DRIVING_NCO_DL0 = Beta('B_FEMALE_DRIVING_DL0', 0, -10, 10, 0, 'B_FEMALE_DRIVING_DL0')
        B_FEMALE_DRIVING_NCO_DL1 = Beta('B_FEMALE_DRIVING_NCO_DL1', 0, -10, 10, 1, 'B_FEMALE_DRIVING_NCO_DL1')
        B_FEMALE_DRIVING_CO1_DL0 = B_FEMALE_DRIVING_NCO_DL0  # Beta('B_FEMALE_DRIVING_CO_DL0',0,-10,10,0)
        B_FEMALE_DRIVING_CO1_DL1 = Beta('B_FEMALE_DRIVING_CO_DL1', 0, -10, 10, 1, 'B_FEMALE_DRIVING_CO_DL1')
        B_FEMALE_DRIVING_CO2_DL0 = B_FEMALE_DRIVING_NCO_DL0  # Beta('B_FEMALE_DRIVING_CO2',0,-10,10,0)
        B_FEMALE_DRIVING_CO2_DL1 = B_FEMALE_DRIVING_CO1_DL1  # Beta('B_FEMALE_DRIVING_CO2',0,-10,10,0)
        B_FEMALE_TRANSIT_NCO_DL0 = Beta('B_FEMALE_TRANSIT_DL0', 0, -10, 10, 0, 'B_FEMALE_TRANSIT_DL0')
        B_FEMALE_TRANSIT_NCO_DL1 = Beta('B_FEMALE_TRANSIT_DL1', 0, -10, 10, 0, 'B_FEMALE_TRANSIT_DL1')
        B_FEMALE_TRANSIT_CO1_DL0 = B_FEMALE_TRANSIT_NCO_DL0  # Beta('B_FEMALE_TRANSIT_CO1',0,-10,10,0)
        B_FEMALE_TRANSIT_CO1_DL1 = B_FEMALE_TRANSIT_NCO_DL1  # Beta('B_FEMALE_TRANSIT_CO1',0,-10,10,0)
        B_FEMALE_TRANSIT_CO2_DL0 = B_FEMALE_TRANSIT_NCO_DL0  # Beta('B_FEMALE_TRANSIT_CO2',0,-10,10,0)
        B_FEMALE_TRANSIT_CO2_DL1 = B_FEMALE_TRANSIT_NCO_DL1  # Beta('B_FEMALE_TRANSIT_CO2',0,-10,10,0)
        B_FEMALE_WALKING_NCO_DL0 = Beta('B_FEMALE_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_FEMALE_WALKING_NCO_DL0')
        B_FEMALE_WALKING_NCO_DL1 = Beta('B_FEMALE_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_FEMALE_WALKING_NCO_DL1')
        B_FEMALE_WALKING_CO1_DL0 = Beta('B_FEMALE_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_FEMALE_WALKING_CO1_DL0')
        B_FEMALE_WALKING_CO1_DL1 = Beta('B_FEMALE_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_FEMALE_WALKING_CO1_DL1')
        B_FEMALE_WALKING_CO2_DL0 = Beta('B_FEMALE_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_FEMALE_WALKING_CO2_DL0')
        B_FEMALE_WALKING_CO2_DL1 = Beta('B_FEMALE_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_FEMALE_WALKING_CO2_DL1')

        B_INTER_PEAK_CYCLING_NCO_DL0 = Beta('B_INTER_PEAK_CYCLING_NCO1_DL0', 0, -10, 10, 1, 'B_INTER_PEAK_CYCLING_NCO1_DL0')
        B_INTER_PEAK_CYCLING_NCO_DL1 = Beta('B_INTER_PEAK_CYCLING_NCO1_DL1', 0, -10, 10, 1, 'B_INTER_PEAK_CYCLING_NCO1_DL1')
        B_INTER_PEAK_CYCLING_CO1_DL0 = B_INTER_PEAK_CYCLING_NCO_DL0  # Beta('B_INTER_PEAK_CYCLING_CO1',0,-10,10,1)
        B_INTER_PEAK_CYCLING_CO1_DL1 = B_INTER_PEAK_CYCLING_NCO_DL1  # Beta('B_INTER_PEAK_CYCLING_CO1',0,-10,10,1)
        B_INTER_PEAK_CYCLING_CO2_DL0 = Beta('B_INTER_PEAK_CYCLING_CO2_DL0', 0, -10, 10, 1, 'B_INTER_PEAK_CYCLING_CO2_DL0')
        B_INTER_PEAK_CYCLING_CO2_DL1 = Beta('B_INTER_PEAK_CYCLING_CO2_DL1', 0, -10, 10, 1, 'B_INTER_PEAK_CYCLING_CO2_DL1')
        B_INTER_PEAK_DRIVING_NCO_DL0 = Beta('B_INTER_PEAK_DRIVING_NCO_DL0', 0, -10, 10, 1, 'B_INTER_PEAK_DRIVING_NCO_DL0')
        B_INTER_PEAK_DRIVING_NCO_DL1 = Beta('B_INTER_PEAK_DRIVING_NCO_DL1', 0, -10, 10, 1, 'B_INTER_PEAK_DRIVING_NCO_DL1')
        B_INTER_PEAK_DRIVING_CO1_DL0 = Beta('B_INTER_PEAK_DRIVING_CO1_DL0', 0, -10, 10, 1, 'B_INTER_PEAK_DRIVING_CO1_DL0')
        B_INTER_PEAK_DRIVING_CO1_DL1 = Beta('B_INTER_PEAK_DRIVING_CO1_DL1', 0, -10, 10, 1, 'B_INTER_PEAK_DRIVING_CO1_DL1')
        B_INTER_PEAK_DRIVING_CO2_DL0 = Beta('B_INTER_PEAK_DRIVING_CO2_DL0', 0, -10, 10, 0, 'B_INTER_PEAK_DRIVING_CO2_DL0')
        B_INTER_PEAK_DRIVING_CO2_DL1 = Beta('B_INTER_PEAK_DRIVING_CO2_DL1', 0, -10, 10, 0, 'B_INTER_PEAK_DRIVING_CO2_DL1')
        # B_INTER_PEAK_TRANSIT_NCO        = Beta('B_INTER_PEAK_TRANSIT_NCO',0,-10,10,0)
        # B_INTER_PEAK_TRANSIT_CO1        = Beta('B_INTER_PEAK_TRANSIT_CO1',0,-10,10,0)
        # B_INTER_PEAK_TRANSIT_CO2        = Beta('B_INTER_PEAK_TRANSIT_CO2',0,-10,10,0)
        B_INTER_PEAK_WALKING_NCO_DL0 = Beta('B_INTER_PEAK_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_INTER_PEAK_WALKING_NCO_DL0')
        B_INTER_PEAK_WALKING_NCO_DL1 = Beta('B_INTER_PEAK_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_INTER_PEAK_WALKING_NCO_DL1')
        B_INTER_PEAK_WALKING_CO1_DL0 = Beta('B_INTER_PEAK_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_INTER_PEAK_WALKING_CO1_DL0')
        B_INTER_PEAK_WALKING_CO1_DL1 = Beta('B_INTER_PEAK_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_INTER_PEAK_WALKING_CO1_DL1')
        B_INTER_PEAK_WALKING_CO2_DL0 = Beta('B_INTER_PEAK_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_INTER_PEAK_WALKING_CO2_DL0')
        B_INTER_PEAK_WALKING_CO2_DL1 = Beta('B_INTER_PEAK_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_INTER_PEAK_WALKING_CO2_DL1')

        B_LOGDISTANCE_CYCLING_NCO_DL0 = Beta('B_LOGDISTANCE_CYCLING', 0, -10, 10, 0, 'B_LOGDISTANCE_CYCLING')
        B_LOGDISTANCE_CYCLING_NCO_DL1 = B_LOGDISTANCE_CYCLING_NCO_DL0  # Beta('B_LOGDISTANCE_CYCLING_DL1',0,-10,10,0)
        B_LOGDISTANCE_CYCLING_CO1_DL0 = B_LOGDISTANCE_CYCLING_NCO_DL0  # Beta('B_LOGDISTANCE_CYCLING_CO1',0,-10,10,0)
        B_LOGDISTANCE_CYCLING_CO1_DL1 = B_LOGDISTANCE_CYCLING_NCO_DL0  # Beta('B_LOGDISTANCE_CYCLING_CO1',0,-10,10,0)
        B_LOGDISTANCE_CYCLING_CO2_DL0 = B_LOGDISTANCE_CYCLING_NCO_DL0  # Beta('B_LOGDISTANCE_CYCLING_CO2',0,-10,10,0)
        B_LOGDISTANCE_CYCLING_CO2_DL1 = B_LOGDISTANCE_CYCLING_NCO_DL0  # Beta('B_LOGDISTANCE_CYCLING_CO2',0,-10,10,0)
        B_LOGDISTANCE_DRIVING_NCO_DL0 = Beta('B_LOGDISTANCE_DRIVING_NCO_DL0', 0, -10, 10, 0, 'B_LOGDISTANCE_DRIVING_NCO_DL0')
        B_LOGDISTANCE_DRIVING_NCO_DL1 = Beta('B_LOGDISTANCE_DRIVING_NCO_DL1', 0, -10, 10, 0, 'B_LOGDISTANCE_DRIVING_NCO_DL1')
        B_LOGDISTANCE_DRIVING_CO1_DL0 = Beta('B_LOGDISTANCE_DRIVING_CO_DL0', 0, -10, 10, 0, 'B_LOGDISTANCE_DRIVING_CO_DL0')
        B_LOGDISTANCE_DRIVING_CO1_DL1 = Beta('B_LOGDISTANCE_DRIVING_CO_DL1', 0, -10, 10, 0, 'B_LOGDISTANCE_DRIVING_CO_DL1')
        B_LOGDISTANCE_DRIVING_CO2_DL0 = B_LOGDISTANCE_DRIVING_CO1_DL0  # Beta('B_LOGDISTANCE_DRIVING_CO2_DL0',0,-10,10,0)
        B_LOGDISTANCE_DRIVING_CO2_DL1 = B_LOGDISTANCE_DRIVING_CO1_DL1  # Beta('B_LOGDISTANCE_DRIVING_CO2_DL1',0,-10,10,0)
        B_LOGDISTANCE_TRANSIT_NCO_DL0 = Beta('B_LOGDISTANCE_TRANSIT_NCO', 0, -10, 10, 0, 'B_LOGDISTANCE_TRANSIT_NCO')
        B_LOGDISTANCE_TRANSIT_NCO_DL1 = B_LOGDISTANCE_TRANSIT_NCO_DL0  # Beta('B_LOGDISTANCE_TRANSIT_NCO_DL1',0,-10,10,0)
        B_LOGDISTANCE_TRANSIT_CO1_DL0 = Beta('B_LOGDISTANCE_TRANSIT_CO', 0, -10, 10, 0, 'B_LOGDISTANCE_TRANSIT_CO')
        B_LOGDISTANCE_TRANSIT_CO1_DL1 = Beta('B_LOGDISTANCE_TRANSIT_CO', 0, -10, 10, 0, 'B_LOGDISTANCE_TRANSIT_CO')
        B_LOGDISTANCE_TRANSIT_CO2_DL0 = B_LOGDISTANCE_TRANSIT_CO1_DL0  # Beta('B_LOGDISTANCE_TRANSIT_CO2',0,-10,10,0)
        B_LOGDISTANCE_TRANSIT_CO2_DL1 = B_LOGDISTANCE_TRANSIT_CO1_DL1  # Beta('B_LOGDISTANCE_TRANSIT_CO2',0,-10,10,0)
        B_LOGDISTANCE_WALKING_NCO_DL0 = Beta('B_LOGDISTANCE_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_LOGDISTANCE_WALKING_NCO_DL0')
        B_LOGDISTANCE_WALKING_NCO_DL1 = Beta('B_LOGDISTANCE_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_LOGDISTANCE_WALKING_NCO_DL1')
        B_LOGDISTANCE_WALKING_CO1_DL0 = Beta('B_LOGDISTANCE_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_LOGDISTANCE_WALKING_CO1_DL0')
        B_LOGDISTANCE_WALKING_CO1_DL1 = Beta('B_LOGDISTANCE_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_LOGDISTANCE_WALKING_CO1_DL1')
        B_LOGDISTANCE_WALKING_CO2_DL0 = Beta('B_LOGDISTANCE_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_LOGDISTANCE_WALKING_CO2_DL0')
        B_LOGDISTANCE_WALKING_CO2_DL1 = Beta('B_LOGDISTANCE_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_LOGDISTANCE_WALKING_CO2_DL1')

        B_PM_PEAK_CYCLING_NCO_DL0 = Beta('B_PM_PEAK_CYCLING_NCO1', 0, -10, 10, 0, 'B_PM_PEAK_CYCLING_NCO1')
        B_PM_PEAK_CYCLING_NCO_DL1 = B_PM_PEAK_CYCLING_NCO_DL0  # Beta('B_PM_PEAK_CYCLING_NCO1_DL1',0,-10,10,0)
        B_PM_PEAK_CYCLING_CO1_DL0 = B_PM_PEAK_CYCLING_NCO_DL0  # Beta('B_PM_PEAK_CYCLING_CO1',0,-10,10,0)
        B_PM_PEAK_CYCLING_CO1_DL1 = B_PM_PEAK_CYCLING_NCO_DL1  # Beta('B_PM_PEAK_CYCLING_CO1',0,-10,10,0)
        B_PM_PEAK_CYCLING_CO2_DL0 = Beta('B_PM_PEAK_CYCLING_CO2_DL0', 0, -10, 10, 1, 'B_PM_PEAK_CYCLING_CO2_DL0')
        B_PM_PEAK_CYCLING_CO2_DL1 = Beta('B_PM_PEAK_CYCLING_CO2_DL1', 0, -10, 10, 1, 'B_PM_PEAK_CYCLING_CO2_DL1')
        B_PM_PEAK_DRIVING_NCO_DL0 = Beta('B_PM_PEAK_DRIVING_DL0', 0, -10, 10, 0, 'B_PM_PEAK_DRIVING_DL0')
        B_PM_PEAK_DRIVING_NCO_DL1 = Beta('B_PM_PEAK_DRIVING_DL1', 0, -10, 10, 0, 'B_PM_PEAK_DRIVING_DL1')
        B_PM_PEAK_DRIVING_CO1_DL0 = B_PM_PEAK_DRIVING_NCO_DL0  # Beta('B_PM_PEAK_DRIVING_CO1',0,-10,10,0)
        B_PM_PEAK_DRIVING_CO1_DL1 = B_PM_PEAK_DRIVING_NCO_DL1  # Beta('B_PM_PEAK_DRIVING_CO1',0,-10,10,0)
        B_PM_PEAK_DRIVING_CO2_DL0 = B_PM_PEAK_DRIVING_NCO_DL0  # Beta('B_PM_PEAK_DRIVING_CO2',0,-10,10,0)
        B_PM_PEAK_DRIVING_CO2_DL1 = B_PM_PEAK_DRIVING_NCO_DL1  # Beta('B_PM_PEAK_DRIVING_CO2',0,-10,10,0)
        B_PM_PEAK_TRANSIT_NCO_DL0 = Beta('B_PM_PEAK_TRANSIT_NCO_DL0', 0, -10, 10, 1, 'B_PM_PEAK_TRANSIT_NCO_DL0')
        B_PM_PEAK_TRANSIT_NCO_DL1 = Beta('B_PM_PEAK_TRANSIT_NCO_DL1', 0, -10, 10, 1, 'B_PM_PEAK_TRANSIT_NCO_DL1')
        B_PM_PEAK_TRANSIT_CO1_DL0 = Beta('B_PM_PEAK_TRANSIT_CO', 0, -10, 10, 0, 'B_PM_PEAK_TRANSIT_CO')
        B_PM_PEAK_TRANSIT_CO1_DL1 = B_PM_PEAK_TRANSIT_CO1_DL0  # Beta('B_PM_PEAK_TRANSIT_CO_DL1',0,-10,10,0)
        B_PM_PEAK_TRANSIT_CO2_DL0 = B_PM_PEAK_TRANSIT_CO1_DL0  # Beta('B_PM_PEAK_TRANSIT_CO2',0,-10,10,0)
        B_PM_PEAK_TRANSIT_CO2_DL1 = B_PM_PEAK_TRANSIT_CO1_DL1  # Beta('B_PM_PEAK_TRANSIT_CO2',0,-10,10,0)
        B_PM_PEAK_WALKING_NCO_DL0 = Beta('B_PM_PEAK_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_PM_PEAK_WALKING_NCO_DL0')
        B_PM_PEAK_WALKING_NCO_DL1 = Beta('B_PM_PEAK_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_PM_PEAK_WALKING_NCO_DL1')
        B_PM_PEAK_WALKING_CO1_DL0 = Beta('B_PM_PEAK_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_PM_PEAK_WALKING_CO1_DL0')
        B_PM_PEAK_WALKING_CO1_DL1 = Beta('B_PM_PEAK_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_PM_PEAK_WALKING_CO1_DL1')
        B_PM_PEAK_WALKING_CO2_DL0 = Beta('B_PM_PEAK_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_PM_PEAK_WALKING_CO2_DL0')
        B_PM_PEAK_WALKING_CO2_DL1 = Beta('B_PM_PEAK_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_PM_PEAK_WALKING_CO2_DL1')

        B_PURPOSE_B_CYCLING_NCO_DL0 = Beta('B_PURPOSE_B_CYCLING', 0, -10, 10, 0, 'B_PURPOSE_B_CYCLING')
        B_PURPOSE_B_CYCLING_NCO_DL1 = B_PURPOSE_B_CYCLING_NCO_DL0  # Beta('B_PURPOSE_B_CYCLING_DL1',0,-10,10,0)
        B_PURPOSE_B_CYCLING_CO1_DL0 = B_PURPOSE_B_CYCLING_NCO_DL0  # Beta('B_PURPOSE_B_CYCLING_CO1',0,-10,10,0)
        B_PURPOSE_B_CYCLING_CO1_DL1 = B_PURPOSE_B_CYCLING_NCO_DL0  # Beta('B_PURPOSE_B_CYCLING_CO1',0,-10,10,0)
        B_PURPOSE_B_CYCLING_CO2_DL0 = B_PURPOSE_B_CYCLING_NCO_DL0  # Beta('B_PURPOSE_B_CYCLING_CO2',0,-10,10,0)
        B_PURPOSE_B_CYCLING_CO2_DL1 = B_PURPOSE_B_CYCLING_NCO_DL0  # Beta('B_PURPOSE_B_CYCLING_CO2',0,-10,10,0)
        B_PURPOSE_B_DRIVING_NCO_DL0 = Beta('B_PURPOSE_B_DRIVING_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_B_DRIVING_NCO_DL0')
        B_PURPOSE_B_DRIVING_NCO_DL1 = Beta('B_PURPOSE_B_DRIVING_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_B_DRIVING_NCO_DL1')
        B_PURPOSE_B_DRIVING_CO1_DL0 = Beta('B_PURPOSE_B_DRIVING_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_B_DRIVING_CO1_DL0')
        B_PURPOSE_B_DRIVING_CO1_DL1 = Beta('B_PURPOSE_B_DRIVING_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_B_DRIVING_CO1_DL1')
        B_PURPOSE_B_DRIVING_CO2_DL0 = Beta('B_PURPOSE_B_DRIVING_CO2', 0, -10, 10, 0, 'B_PURPOSE_B_DRIVING_CO2')
        B_PURPOSE_B_DRIVING_CO2_DL1 = B_PURPOSE_B_DRIVING_CO2_DL0  # Beta('B_PURPOSE_B_DRIVING_CO2_DL1',0,-10,10,0)
        B_PURPOSE_B_TRANSIT_NCO_DL0 = Beta('B_PURPOSE_B_TRANSIT_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_B_TRANSIT_NCO_DL0')
        B_PURPOSE_B_TRANSIT_NCO_DL1 = Beta('B_PURPOSE_B_TRANSIT_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_B_TRANSIT_NCO_DL1')
        B_PURPOSE_B_TRANSIT_CO1_DL0 = Beta('B_PURPOSE_B_TRANSIT_CO_DL0', 0, -10, 10, 0, 'B_PURPOSE_B_TRANSIT_CO_DL0')
        B_PURPOSE_B_TRANSIT_CO1_DL1 = Beta('B_PURPOSE_B_TRANSIT_CO_DL1', 0, -10, 10, 0, 'B_PURPOSE_B_TRANSIT_CO_DL1')
        B_PURPOSE_B_TRANSIT_CO2_DL0 = B_PURPOSE_B_TRANSIT_CO1_DL0  # Beta('B_PURPOSE_B_TRANSIT_CO2',0,-10,10,0)
        B_PURPOSE_B_TRANSIT_CO2_DL1 = B_PURPOSE_B_TRANSIT_CO1_DL1  # Beta('B_PURPOSE_B_TRANSIT_CO2',0,-10,10,0)
        B_PURPOSE_B_WALKING_NCO_DL0 = Beta('B_PURPOSE_B_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_B_WALKING_NCO_DL0')
        B_PURPOSE_B_WALKING_NCO_DL1 = Beta('B_PURPOSE_B_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_B_WALKING_NCO_DL1')
        B_PURPOSE_B_WALKING_CO1_DL0 = Beta('B_PURPOSE_B_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_B_WALKING_CO1_DL0')
        B_PURPOSE_B_WALKING_CO1_DL1 = Beta('B_PURPOSE_B_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_B_WALKING_CO1_DL1')
        B_PURPOSE_B_WALKING_CO2_DL0 = Beta('B_PURPOSE_B_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_PURPOSE_B_WALKING_CO2_DL0')
        B_PURPOSE_B_WALKING_CO2_DL1 = Beta('B_PURPOSE_B_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_PURPOSE_B_WALKING_CO2_DL1')

        # B_PURPOSE_HBE_CYCLING_NCO   = Beta('B_PURPOSE_HBE_CYCLING_NCO',0,-10,10,0)
        # B_PURPOSE_HBE_CYCLING_CO1   = Beta('B_PURPOSE_HBE_CYCLING_CO1',0,-10,10,0)
        # B_PURPOSE_HBE_CYCLING_CO2   = Beta('B_PURPOSE_HBE_CYCLING_CO2',0,-10,10,0)
        B_PURPOSE_HBE_DRIVING_NCO_DL0 = Beta('B_PURPOSE_HBE_DRIVING_NCO', 0, -10, 10, 0, 'B_PURPOSE_HBE_DRIVING_NCO')
        B_PURPOSE_HBE_DRIVING_NCO_DL1 = B_PURPOSE_HBE_DRIVING_NCO_DL0  # Beta('B_PURPOSE_HBE_DRIVING_NCO_DL1',0,-10,10,0)
        B_PURPOSE_HBE_DRIVING_CO1_DL0 = Beta('B_PURPOSE_HBE_DRIVING_CO_DL0', 0, -10, 10, 0, 'B_PURPOSE_HBE_DRIVING_CO_DL0')
        B_PURPOSE_HBE_DRIVING_CO1_DL1 = Beta('B_PURPOSE_HBE_DRIVING_CO1_DL1', 0, -10, 10, 0, 'B_PURPOSE_HBE_DRIVING_CO1_DL1')
        B_PURPOSE_HBE_DRIVING_CO2_DL0 = B_PURPOSE_HBE_DRIVING_CO1_DL0  # Beta('B_PURPOSE_HBE_DRIVING_CO2_DL0',0,-10,10,0)
        B_PURPOSE_HBE_DRIVING_CO2_DL1 = Beta('B_PURPOSE_HBE_DRIVING_CO2_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBE_DRIVING_CO2_DL1')
        B_PURPOSE_HBE_TRANSIT_NCO_DL0 = Beta('B_PURPOSE_HBE_TRANSIT_DL0', 0, -10, 10, 0, 'B_PURPOSE_HBE_TRANSIT_DL0')
        B_PURPOSE_HBE_TRANSIT_NCO_DL1 = Beta('B_PURPOSE_HBE_TRANSIT_NCO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBE_TRANSIT_NCO1_DL1')
        B_PURPOSE_HBE_TRANSIT_CO1_DL0 = B_PURPOSE_HBE_TRANSIT_NCO_DL0  # Beta('B_PURPOSE_HBE_TRANSIT_CO1',0,-10,10,0)
        B_PURPOSE_HBE_TRANSIT_CO1_DL1 = B_PURPOSE_HBE_TRANSIT_NCO_DL1  # Beta('B_PURPOSE_HBE_TRANSIT_CO1',0,-10,10,0)
        B_PURPOSE_HBE_TRANSIT_CO2_DL0 = B_PURPOSE_HBE_TRANSIT_NCO_DL0  # Beta('B_PURPOSE_HBE_TRANSIT_CO2_DL0',0,-10,10,0)
        B_PURPOSE_HBE_TRANSIT_CO2_DL1 = Beta('B_PURPOSE_HBE_TRANSIT_CO2_DL1', 0, -10, 10, 0, 'B_PURPOSE_HBE_TRANSIT_CO2_DL1')
        B_PURPOSE_HBE_WALKING_NCO_DL0 = Beta('B_PURPOSE_HBE_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBE_WALKING_NCO_DL0')
        B_PURPOSE_HBE_WALKING_NCO_DL1 = Beta('B_PURPOSE_HBE_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBE_WALKING_NCO_DL1')
        B_PURPOSE_HBE_WALKING_CO1_DL0 = Beta('B_PURPOSE_HBE_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBE_WALKING_CO1_DL0')
        B_PURPOSE_HBE_WALKING_CO1_DL1 = Beta('B_PURPOSE_HBE_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBE_WALKING_CO1_DL1')
        B_PURPOSE_HBE_WALKING_CO2_DL0 = Beta('B_PURPOSE_HBE_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBE_WALKING_CO2_DL0')
        B_PURPOSE_HBE_WALKING_CO2_DL1 = Beta('B_PURPOSE_HBE_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBE_WALKING_CO2_DL1')

        B_PURPOSE_HBO_CYCLING_NCO_DL0 = Beta('B_PURPOSE_HBO_CYCLING_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_CYCLING_NCO_DL0')
        B_PURPOSE_HBO_CYCLING_NCO_DL1 = Beta('B_PURPOSE_HBO_CYCLING_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_CYCLING_NCO_DL1')
        B_PURPOSE_HBO_CYCLING_CO1_DL0 = Beta('B_PURPOSE_HBO_CYCLING_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_CYCLING_CO1_DL0')
        B_PURPOSE_HBO_CYCLING_CO1_DL1 = Beta('B_PURPOSE_HBO_CYCLING_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_CYCLING_CO1_DL1')
        B_PURPOSE_HBO_CYCLING_CO2_DL0 = Beta('B_PURPOSE_HBO_CYCLING_CO2', 0, -10, 10, 0, 'B_PURPOSE_HBO_CYCLING_CO2')
        B_PURPOSE_HBO_CYCLING_CO2_DL1 = B_PURPOSE_HBO_CYCLING_CO2_DL0  # Beta('B_PURPOSE_HBO_CYCLING_CO2_DL1',0,-10,10,0)
        B_PURPOSE_HBO_DRIVING_NCO_DL0 = Beta('B_PURPOSE_HBO_DRIVING_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_DRIVING_NCO_DL0')
        B_PURPOSE_HBO_DRIVING_NCO_DL1 = Beta('B_PURPOSE_HBO_DRIVING_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_DRIVING_NCO_DL1')
        B_PURPOSE_HBO_DRIVING_CO1_DL0 = Beta('B_PURPOSE_HBO_DRIVING_CO_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_DRIVING_CO_DL0')
        B_PURPOSE_HBO_DRIVING_CO1_DL1 = Beta('B_PURPOSE_HBO_DRIVING_CO_DL1', 0, -10, 10, 0, 'B_PURPOSE_HBO_DRIVING_CO_DL1')
        B_PURPOSE_HBO_DRIVING_CO2_DL0 = B_PURPOSE_HBO_DRIVING_CO1_DL0  # Beta('B_PURPOSE_HBO_DRIVING_CO2',0,-10,10,0)
        B_PURPOSE_HBO_DRIVING_CO2_DL1 = B_PURPOSE_HBO_DRIVING_CO1_DL1  # Beta('B_PURPOSE_HBO_DRIVING_CO2',0,-10,10,0)
        B_PURPOSE_HBO_TRANSIT_NCO_DL0 = Beta('B_PURPOSE_HBO_TRANSIT_NCO_DL0', 0, -10, 10, 0, 'B_PURPOSE_HBO_TRANSIT_NCO_DL0')
        B_PURPOSE_HBO_TRANSIT_NCO_DL1 = Beta('B_PURPOSE_HBO_TRANSIT_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_TRANSIT_NCO_DL1')
        B_PURPOSE_HBO_TRANSIT_CO1_DL0 = Beta('B_PURPOSE_HBO_TRANSIT_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_TRANSIT_CO1_DL0')
        B_PURPOSE_HBO_TRANSIT_CO1_DL1 = Beta('B_PURPOSE_HBO_TRANSIT_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_TRANSIT_CO1_DL1')
        B_PURPOSE_HBO_TRANSIT_CO2_DL0 = Beta('B_PURPOSE_HBO_TRANSIT_CO2_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_TRANSIT_CO2_DL0')
        B_PURPOSE_HBO_TRANSIT_CO2_DL1 = Beta('B_PURPOSE_HBO_TRANSIT_CO2_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_TRANSIT_CO2_DL1')
        B_PURPOSE_HBO_WALKING_NCO_DL0 = Beta('B_PURPOSE_HBO_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_WALKING_NCO_DL0')
        B_PURPOSE_HBO_WALKING_NCO_DL1 = Beta('B_PURPOSE_HBO_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_WALKING_NCO_DL1')
        B_PURPOSE_HBO_WALKING_CO1_DL0 = Beta('B_PURPOSE_HBO_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_WALKING_CO1_DL0')
        B_PURPOSE_HBO_WALKING_CO1_DL1 = Beta('B_PURPOSE_HBO_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_WALKING_CO1_DL1')
        B_PURPOSE_HBO_WALKING_CO2_DL0 = Beta('B_PURPOSE_HBO_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBO_WALKING_CO2_DL0')
        B_PURPOSE_HBO_WALKING_CO2_DL1 = Beta('B_PURPOSE_HBO_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBO_WALKING_CO2_DL1')

        B_PURPOSE_HBW_CYCLING_NCO_DL0 = Beta('B_PURPOSE_HBW_CYCLING_NCO1', 0, -10, 10, 0, 'B_PURPOSE_HBW_CYCLING_NCO1')
        B_PURPOSE_HBW_CYCLING_NCO_DL1 = B_PURPOSE_HBW_CYCLING_NCO_DL0  # Beta('B_PURPOSE_HBW_CYCLING_NCO1_DL1',0,-10,10,0)
        B_PURPOSE_HBW_CYCLING_CO1_DL0 = B_PURPOSE_HBW_CYCLING_NCO_DL0  # Beta('B_PURPOSE_HBW_CYCLING_CO1',0,-10,10,0)
        B_PURPOSE_HBW_CYCLING_CO1_DL1 = B_PURPOSE_HBW_CYCLING_NCO_DL0  # Beta('B_PURPOSE_HBW_CYCLING_CO1',0,-10,10,0)
        B_PURPOSE_HBW_CYCLING_CO2_DL0 = Beta('B_PURPOSE_HBW_CYCLING_CO2_DL0', 0, -100, 100, 1, 'B_PURPOSE_HBW_CYCLING_CO2_DL0')
        B_PURPOSE_HBW_CYCLING_CO2_DL1 = Beta('B_PURPOSE_HBW_CYCLING_CO2_DL1', 0, -100, 100, 0, 'B_PURPOSE_HBW_CYCLING_CO2_DL1')
        B_PURPOSE_HBW_DRIVING_NCO_DL0 = Beta('B_PURPOSE_HBW_DRIVING_NCO', 0, -10, 10, 0, 'B_PURPOSE_HBW_DRIVING_NCO')
        B_PURPOSE_HBW_DRIVING_NCO_DL1 = B_PURPOSE_HBW_DRIVING_NCO_DL0  # Beta('B_PURPOSE_HBW_DRIVING_NCO_DL1',0,-10,10,0)
        B_PURPOSE_HBW_DRIVING_CO1_DL0 = Beta('B_PURPOSE_HBW_DRIVING_CO1_DL0', 0, -10, 10, 0, 'B_PURPOSE_HBW_DRIVING_CO1_DL0')
        B_PURPOSE_HBW_DRIVING_CO1_DL1 = Beta('B_PURPOSE_HBW_DRIVING_CO1_DL1', 0, -10, 10, 0, 'B_PURPOSE_HBW_DRIVING_CO1_DL1')
        B_PURPOSE_HBW_DRIVING_CO2_DL0 = Beta('B_PURPOSE_HBW_DRIVING_CO2_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBW_DRIVING_CO2_DL0')
        B_PURPOSE_HBW_DRIVING_CO2_DL1 = Beta('B_PURPOSE_HBW_DRIVING_CO2_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBW_DRIVING_CO2_DL1')
        B_PURPOSE_HBW_TRANSIT_NCO_DL0 = Beta('B_PURPOSE_HBW_TRANSIT_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBW_TRANSIT_NCO_DL0')
        B_PURPOSE_HBW_TRANSIT_NCO_DL1 = Beta('B_PURPOSE_HBW_TRANSIT_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBW_TRANSIT_NCO_DL1')
        B_PURPOSE_HBW_TRANSIT_CO1_DL0 = Beta('B_PURPOSE_HBW_TRANSIT_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBW_TRANSIT_CO1_DL0')
        B_PURPOSE_HBW_TRANSIT_CO1_DL1 = Beta('B_PURPOSE_HBW_TRANSIT_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBW_TRANSIT_CO1_DL1')
        B_PURPOSE_HBW_TRANSIT_CO2_DL0 = Beta('B_PURPOSE_HBW_TRANSIT_CO2_DL0', 0, -10, 10, 0, 'B_PURPOSE_HBW_TRANSIT_CO2_DL0')
        B_PURPOSE_HBW_TRANSIT_CO2_DL1 = Beta('B_PURPOSE_HBW_TRANSIT_CO2_DL1', 0, -10, 10, 0, 'B_PURPOSE_HBW_TRANSIT_CO2_DL1')
        B_PURPOSE_HBW_WALKING_NCO_DL0 = Beta('B_PURPOSE_HBW_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBW_WALKING_NCO_DL0')
        B_PURPOSE_HBW_WALKING_NCO_DL1 = Beta('B_PURPOSE_HBW_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBW_WALKING_NCO_DL1')
        B_PURPOSE_HBW_WALKING_CO1_DL0 = Beta('B_PURPOSE_HBW_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBW_WALKING_CO1_DL0')
        B_PURPOSE_HBW_WALKING_CO1_DL1 = Beta('B_PURPOSE_HBW_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBW_WALKING_CO1_DL1')
        B_PURPOSE_HBW_WALKING_CO2_DL0 = Beta('B_PURPOSE_HBW_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_PURPOSE_HBW_WALKING_CO2_DL0')
        B_PURPOSE_HBW_WALKING_CO2_DL1 = Beta('B_PURPOSE_HBW_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_PURPOSE_HBW_WALKING_CO2_DL1')

        B_SATURDAY_CYCLING_NCO_DL0 = Beta('B_SATURDAY_CYCLING_NCO_DL0', 0, -10, 10, 1, 'B_SATURDAY_CYCLING_NCO_DL0')
        B_SATURDAY_CYCLING_NCO_DL1 = Beta('B_SATURDAY_CYCLING_NCO_DL1', 0, -10, 10, 0, 'B_SATURDAY_CYCLING_NCO_DL1')
        B_SATURDAY_CYCLING_CO1_DL0 = Beta('B_SATURDAY_CYCLING_CO1_DL0', 0, -10, 10, 1, 'B_SATURDAY_CYCLING_CO1_DL0')
        B_SATURDAY_CYCLING_CO1_DL1 = Beta('B_SATURDAY_CYCLING_CO1_DL1', 0, -10, 10, 1, 'B_SATURDAY_CYCLING_CO1_DL1')
        B_SATURDAY_CYCLING_CO2_DL0 = Beta('B_SATURDAY_CYCLING_CO2_DL0', 0, -10, 10, 1, 'B_SATURDAY_CYCLING_CO2_DL0')
        B_SATURDAY_CYCLING_CO2_DL1 = Beta('B_SATURDAY_CYCLING_CO2_DL1', 0, -10, 10, 1, 'B_SATURDAY_CYCLING_CO2_DL1')
        # B_SATURDAY_DRIVING_NCO      = Beta('B_SATURDAY_DRIVING_NCO',0,-10,10,0)
        # B_SATURDAY_DRIVING_CO1      = Beta('B_SATURDAY_DRIVING_CO1',0,-10,10,0)
        # B_SATURDAY_DRIVING_CO2      = Beta('B_SATURDAY_DRIVING_CO2',0,-10,10,0)
        B_SATURDAY_TRANSIT_NCO_DL0 = Beta('B_SATURDAY_TRANSIT_NCO_DL0', 0, -10, 10, 1, 'B_SATURDAY_TRANSIT_NCO_DL0')
        B_SATURDAY_TRANSIT_NCO_DL1 = Beta('B_SATURDAY_TRANSIT_NCO_DL1', 0, -10, 10, 1, 'B_SATURDAY_TRANSIT_NCO_DL1')
        B_SATURDAY_TRANSIT_CO1_DL0 = Beta('B_SATURDAY_TRANSIT_CO', 0, -10, 10, 0, 'B_SATURDAY_TRANSIT_CO')
        B_SATURDAY_TRANSIT_CO1_DL1 = B_SATURDAY_TRANSIT_CO1_DL0  # Beta('B_SATURDAY_TRANSIT_CO_DL1',0,-10,10,0)
        B_SATURDAY_TRANSIT_CO2_DL0 = B_SATURDAY_TRANSIT_CO1_DL0  # Beta('B_SATURDAY_TRANSIT_CO2',0,-10,10,0)
        B_SATURDAY_TRANSIT_CO2_DL1 = B_SATURDAY_TRANSIT_CO1_DL0  # Beta('B_SATURDAY_TRANSIT_CO2',0,-10,10,0)
        B_SATURDAY_WALKING_NCO_DL0 = Beta('B_SATURDAY_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_SATURDAY_WALKING_NCO_DL0')
        B_SATURDAY_WALKING_NCO_DL1 = Beta('B_SATURDAY_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_SATURDAY_WALKING_NCO_DL1')
        B_SATURDAY_WALKING_CO1_DL0 = Beta('B_SATURDAY_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_SATURDAY_WALKING_CO1_DL0')
        B_SATURDAY_WALKING_CO1_DL1 = Beta('B_SATURDAY_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_SATURDAY_WALKING_CO1_DL1')
        B_SATURDAY_WALKING_CO2_DL0 = Beta('B_SATURDAY_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_SATURDAY_WALKING_CO2_DL0')
        B_SATURDAY_WALKING_CO2_DL1 = Beta('B_SATURDAY_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_SATURDAY_WALKING_CO2_DL1')

        B_TIME_ACCESS_NCO_DL0 = Beta('B_TIME_ACCESS_NCO_DL0', 0, -10, 10, 0, 'B_TIME_ACCESS_NCO_DL0')
        B_TIME_ACCESS_NCO_DL1 = Beta('B_TIME_ACCESS_NCO_DL1', 0, -10, 10, 0, 'B_TIME_ACCESS_NCO_DL1')
        B_TIME_ACCESS_CO1_DL0 = Beta('B_TIME_ACCESS_CO', 0, -10, 10, 0, 'B_TIME_ACCESS_CO')
        B_TIME_ACCESS_CO1_DL1 = B_TIME_ACCESS_CO1_DL0  # Beta('B_TIME_ACCESS_CO_DL1',0,-10,10,0)
        B_TIME_ACCESS_CO2_DL0 = B_TIME_ACCESS_CO1_DL0  # Beta('B_TIME_ACCESS_CO2',0,-10,10,0)
        B_TIME_ACCESS_CO2_DL1 = B_TIME_ACCESS_CO1_DL0  # Beta('B_TIME_ACCESS_CO2',0,-10,10,0)
        B_TIME_BUS_NCO_DL0 = Beta('B_TIME_BUS_NCO1_DL0', 0, -10, 10, 0, 'B_TIME_BUS_NCO1_DL0')
        B_TIME_BUS_NCO_DL1 = Beta('B_TIME_BUS_NCO1_DL1', 0, -10, 10, 0, 'B_TIME_BUS_NCO1_DL1')
        B_TIME_BUS_CO1_DL0 = B_TIME_BUS_NCO_DL0  # Beta('B_TIME_BUS_CO1',0,-10,10,0)
        B_TIME_BUS_CO1_DL1 = B_TIME_BUS_NCO_DL1  # Beta('B_TIME_BUS_CO1',0,-10,10,0)
        B_TIME_BUS_CO2_DL0 = Beta('B_TIME_BUS_CO2_DL0', 0, -10, 10, 0, 'B_TIME_BUS_CO2_DL0')
        B_TIME_BUS_CO2_DL1 = Beta('B_TIME_BUS_CO2_DL1', 0, -10, 10, 0, 'B_TIME_BUS_CO2_DL1')
        B_TIME_CYCLING_NCO_DL0 = Beta('B_TIME_CYCLING_NCO_DL0', 0, -10, 10, 1, 'B_TIME_CYCLING_NCO_DL0')
        B_TIME_CYCLING_NCO_DL1 = Beta('B_TIME_CYCLING_NCO_DL1', 0, -10, 10, 1, 'B_TIME_CYCLING_NCO_DL1')
        B_TIME_CYCLING_CO1_DL0 = Beta('B_TIME_CYCLING_CO1', 0, -10, 10, 1, 'B_TIME_CYCLING_CO1')
        B_TIME_CYCLING_CO1_DL1 = B_TIME_CYCLING_CO1_DL0  # Beta('B_TIME_CYCLING_CO1_DL1',0,-10,10,1)
        B_TIME_CYCLING_CO2_DL0 = Beta('B_TIME_CYCLING_CO2_DL0', 0, -10, 10, 1, 'B_TIME_CYCLING_CO2_DL0')
        B_TIME_CYCLING_CO2_DL1 = Beta('B_TIME_CYCLING_CO2_DL1', 0, -10, 10, 1, 'B_TIME_CYCLING_CO2_DL1')
        B_TIME_DRIVING_NCO_DL0 = Beta('B_TIME_DRIVING_NCO', 0, -10, 10, 0, 'B_TIME_DRIVING_NCO')
        B_TIME_DRIVING_NCO_DL1 = B_TIME_DRIVING_NCO_DL0  # Beta('B_TIME_DRIVING_NCO_DL1',0,-10,10,0)
        B_TIME_DRIVING_CO1_DL0 = Beta('B_TIME_DRIVING_CO1_DL0', 0, -10, 10, 0, 'B_TIME_DRIVING_CO1_DL0')
        B_TIME_DRIVING_CO1_DL1 = Beta('B_TIME_DRIVING_CO1_DL1', 0, -10, 10, 0, 'B_TIME_DRIVING_CO1_DL1')
        B_TIME_DRIVING_CO2_DL0 = Beta('B_TIME_DRIVING_CO2_DL0', 0, -10, 10, 0, 'B_TIME_DRIVING_CO2_DL0')
        B_TIME_DRIVING_CO2_DL1 = Beta('B_TIME_DRIVING_CO2_DL1', 0, -10, 10, 0, 'B_TIME_DRIVING_CO2_DL1')
        B_TIME_INT_WAIT_NCO_DL0 = Beta('B_TIME_INT_WAIT_NCO', 0, -10, 10, 0, 'B_TIME_INT_WAIT_NCO')
        B_TIME_INT_WAIT_NCO_DL1 = B_TIME_INT_WAIT_NCO_DL0  # Beta('B_TIME_INT_WAIT_NCO_DL1',0,-10,10,0)
        B_TIME_INT_WAIT_CO1_DL0 = Beta('B_TIME_INT_WAIT_CO', 0, -10, 10, 0, 'B_TIME_INT_WAIT_CO')
        B_TIME_INT_WAIT_CO1_DL1 = B_TIME_INT_WAIT_CO1_DL0  # Beta('B_TIME_INT_WAIT_CO_DL1',0,-10,10,0)
        B_TIME_INT_WAIT_CO2_DL0 = B_TIME_INT_WAIT_CO1_DL0  # Beta('B_TIME_INT_WAIT_CO2',0,-10,10,0)
        B_TIME_INT_WAIT_CO2_DL1 = B_TIME_INT_WAIT_CO1_DL0  # Beta('B_TIME_INT_WAIT_CO2',0,-10,10,0)
        B_TIME_INT_WALK_NCO_DL0 = Beta('B_TIME_INT_WALK_NCO_DL0', 0, -10, 10, 1, 'B_TIME_INT_WALK_NCO_DL0')
        B_TIME_INT_WALK_NCO_DL1 = Beta('B_TIME_INT_WALK_NCO_DL1', 0, -10, 10, 1, 'B_TIME_INT_WALK_NCO_DL1')
        B_TIME_INT_WALK_CO1_DL0 = Beta('B_TIME_INT_WALK_CO1', 0, -10, 10, 0, 'B_TIME_INT_WALK_CO1')
        B_TIME_INT_WALK_CO1_DL1 = B_TIME_INT_WALK_CO1_DL0  # Beta('B_TIME_INT_WALK_CO1_DL1',0,-10,10,0)
        B_TIME_INT_WALK_CO2_DL0 = Beta('B_TIME_INT_WALK_CO2_DL0', 0, -10, 10, 1, 'B_TIME_INT_WALK_CO2_DL0')
        B_TIME_INT_WALK_CO2_DL1 = Beta('B_TIME_INT_WALK_CO2_DL1', 0, -10, 10, 1, 'B_TIME_INT_WALK_CO2_DL1')
        B_TIME_RAIL_NCO_DL0 = Beta('B_TIME_RAIL', 0, -10, 10, 0, 'B_TIME_RAIL')
        B_TIME_RAIL_NCO_DL1 = B_TIME_RAIL_NCO_DL0  # Beta('B_TIME_RAIL_DL1',0,-10,10,0)
        B_TIME_RAIL_CO1_DL0 = B_TIME_RAIL_NCO_DL0  # Beta('B_TIME_RAIL_CO1',0,-10,10,0)
        B_TIME_RAIL_CO1_DL1 = B_TIME_RAIL_NCO_DL0  # Beta('B_TIME_RAIL_CO1',0,-10,10,0)
        B_TIME_RAIL_CO2_DL0 = B_TIME_RAIL_NCO_DL0  # Beta('B_TIME_RAIL_CO2',0,-10,10,0)
        B_TIME_RAIL_CO2_DL1 = B_TIME_RAIL_NCO_DL0  # Beta('B_TIME_RAIL_CO2',0,-10,10,0)
        B_TIME_WALKING_NCO_DL0 = Beta('B_TIME_WALKING_DL0', 0, -10, 10, 0, 'B_TIME_WALKING_DL0')
        B_TIME_WALKING_NCO_DL1 = Beta('B_TIME_WALKING_DL1', 0, -10, 10, 0, 'B_TIME_WALKING_DL1')
        B_TIME_WALKING_CO1_DL0 = B_TIME_WALKING_NCO_DL0  # Beta('B_TIME_WALKING_CO1',0,-10,10,0)
        B_TIME_WALKING_CO1_DL1 = B_TIME_WALKING_NCO_DL1  # Beta('B_TIME_WALKING_CO1',0,-10,10,0)
        B_TIME_WALKING_CO2_DL0 = B_TIME_WALKING_NCO_DL0  # Beta('B_TIME_WALKING_CO2',0,-10,10,0)
        B_TIME_WALKING_CO2_DL1 = B_TIME_WALKING_NCO_DL1  # Beta('B_TIME_WALKING_CO2',0,-10,10,0)

        B_TRAFFIC_NCO_DL0 = Beta('B_TRAFFIC_DL0', 0, -10, 10, 0, 'B_TRAFFIC_DL0')
        B_TRAFFIC_NCO_DL1 = Beta('B_TRAFFIC_NCO1_DL1', 0, -10, 10, 0, 'B_TRAFFIC_NCO1_DL1')
        B_TRAFFIC_CO1_DL0 = B_TRAFFIC_NCO_DL0  # Beta('B_TRAFFIC_CO1',0,-10,10,0)
        B_TRAFFIC_CO1_DL1 = B_TRAFFIC_NCO_DL1  # Beta('B_TRAFFIC_CO1',0,-10,10,0)
        B_TRAFFIC_CO2_DL0 = B_TRAFFIC_NCO_DL0  # Beta('B_TRAFFIC_CO2_DL0',0,-10,10,0)
        B_TRAFFIC_CO2_DL1 = Beta('B_TRAFFIC_CO2_DL1', 0, -10, 10, 0, 'B_TRAFFIC_CO2_DL1')

        # B_WEEKDAY_CYCLING_NCO       = Beta('B_WEEKDAY_CYCLING_NCO',0,-10,10,0)
        # B_WEEKDAY_CYCLING_CO1       = Beta('B_WEEKDAY_CYCLING_CO1',0,-10,10,0)
        # B_WEEKDAY_CYCLING_CO2           = Beta('B_WEEKDAY_CYCLING_CO2',0,-10,10,0)
        B_WEEKDAY_DRIVING_NCO_DL0 = Beta('B_WEEKDAY_DRIVING_NCO1_DL0', 0, -10, 10, 0, 'B_WEEKDAY_DRIVING_NCO1_DL0')
        B_WEEKDAY_DRIVING_NCO_DL1 = Beta('B_WEEKDAY_DRIVING_NCO1_DL1', 0, -10, 10, 0, 'B_WEEKDAY_DRIVING_NCO1_DL1')
        B_WEEKDAY_DRIVING_CO1_DL0 = B_WEEKDAY_DRIVING_NCO_DL0  # Beta('B_WEEKDAY_DRIVING_CO1',0,-10,10,0)
        B_WEEKDAY_DRIVING_CO1_DL1 = B_WEEKDAY_DRIVING_NCO_DL1  # Beta('B_WEEKDAY_DRIVING_CO1',0,-10,10,0)
        B_WEEKDAY_DRIVING_CO2_DL0 = Beta('B_WEEKDAY_DRIVING_CO2_DL0', 0, -10, 10, 1, 'B_WEEKDAY_DRIVING_CO2_DL0')
        B_WEEKDAY_DRIVING_CO2_DL1 = Beta('B_WEEKDAY_DRIVING_CO2_DL1', 0, -10, 10, 1, 'B_WEEKDAY_DRIVING_CO2_DL1')
        B_WEEKDAY_TRANSIT_NCO_DL0 = Beta('B_WEEKDAY_TRANSIT_NCO_DL0', 0, -10, 10, 1, 'B_WEEKDAY_TRANSIT_NCO_DL0')
        B_WEEKDAY_TRANSIT_NCO_DL1 = Beta('B_WEEKDAY_TRANSIT_NCO_DL1', 0, -10, 10, 1, 'B_WEEKDAY_TRANSIT_NCO_DL1')
        B_WEEKDAY_TRANSIT_CO1_DL0 = Beta('B_WEEKDAY_TRANSIT_CO', 0, -10, 10, 0, 'B_WEEKDAY_TRANSIT_CO')
        B_WEEKDAY_TRANSIT_CO1_DL1 = B_WEEKDAY_TRANSIT_CO1_DL0  # Beta('B_WEEKDAY_TRANSIT_CO_DL1',0,-10,10,0)
        B_WEEKDAY_TRANSIT_CO2_DL0 = B_WEEKDAY_TRANSIT_CO1_DL0  # Beta('B_WEEKDAY_TRANSIT_CO2',0,-10,10,0)
        B_WEEKDAY_TRANSIT_CO2_DL1 = B_WEEKDAY_TRANSIT_CO1_DL0  # Beta('B_WEEKDAY_TRANSIT_CO2',0,-10,10,0)
        B_WEEKDAY_WALKING_NCO_DL0 = Beta('B_WEEKDAY_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_WEEKDAY_WALKING_NCO_DL0')
        B_WEEKDAY_WALKING_NCO_DL1 = Beta('B_WEEKDAY_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_WEEKDAY_WALKING_NCO_DL1')
        B_WEEKDAY_WALKING_CO1_DL0 = Beta('B_WEEKDAY_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_WEEKDAY_WALKING_CO1_DL0')
        B_WEEKDAY_WALKING_CO1_DL1 = Beta('B_WEEKDAY_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_WEEKDAY_WALKING_CO1_DL1')
        B_WEEKDAY_WALKING_CO2_DL0 = Beta('B_WEEKDAY_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_WEEKDAY_WALKING_CO2_DL0')
        B_WEEKDAY_WALKING_CO2_DL1 = Beta('B_WEEKDAY_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_WEEKDAY_WALKING_CO2_DL1')

        B_WINTER_CYCLING_NCO_DL0 = Beta('B_WINTER_CYCLING_NCO_DL0', 0, -10, 10, 1, 'B_WINTER_CYCLING_NCO_DL0')
        B_WINTER_CYCLING_NCO_DL1 = Beta('B_WINTER_CYCLING_NCO_DL1', 0, -10, 10, 1, 'B_WINTER_CYCLING_NCO_DL1')
        B_WINTER_CYCLING_CO1_DL0 = Beta('B_WINTER_CYCLING_CO_DL0', 0, -10, 10, 1, 'B_WINTER_CYCLING_CO_DL0')
        B_WINTER_CYCLING_CO1_DL1 = Beta('B_WINTER_CYCLING_CO_DL1', 0, -10, 10, 0, 'B_WINTER_CYCLING_CO_DL1')
        B_WINTER_CYCLING_CO2_DL0 = B_WINTER_CYCLING_CO1_DL0  # Beta('B_WINTER_CYCLING_CO2',0,-10,10,0)
        B_WINTER_CYCLING_CO2_DL1 = B_WINTER_CYCLING_CO1_DL1  # Beta('B_WINTER_CYCLING_CO2',0,-10,10,0)
        B_WINTER_DRIVING_NCO_DL0 = Beta('B_WINTER_DRIVING_NCO_DL0', 0, -10, 10, 1, 'B_WINTER_DRIVING_NCO_DL0')
        B_WINTER_DRIVING_NCO_DL1 = Beta('B_WINTER_DRIVING_NCO_DL1', 0, -10, 10, 1, 'B_WINTER_DRIVING_NCO_DL1')
        B_WINTER_DRIVING_CO1_DL0 = Beta('B_WINTER_DRIVING_CO', 0, -10, 10, 0, 'B_WINTER_DRIVING_CO')
        B_WINTER_DRIVING_CO1_DL1 = B_WINTER_DRIVING_CO1_DL0  # Beta('B_WINTER_DRIVING_CO_DL1',0,-10,10,0)
        B_WINTER_DRIVING_CO2_DL0 = B_WINTER_DRIVING_CO1_DL0  # Beta('B_WINTER_DRIVING_CO2',0,-10,10,0)
        B_WINTER_DRIVING_CO2_DL1 = B_WINTER_DRIVING_CO1_DL0  # Beta('B_WINTER_DRIVING_CO2',0,-10,10,0)
        # B_WINTER_TRANSIT_NCO        = Beta('B_WINTER_TRANSIT_NCO',0,-10,10,0)
        # B_WINTER_TRANSIT_CO1        = Beta('B_WINTER_TRANSIT_CO1',0,-10,10,0)
        # B_WINTER_TRANSIT_CO2        = Beta('B_WINTER_TRANSIT_CO2',0,-10,10,0)
        B_WINTER_WALKING_NCO_DL0 = Beta('B_WINTER_WALKING_NCO_DL0', 0, -10, 10, 1, 'B_WINTER_WALKING_NCO_DL0')
        B_WINTER_WALKING_NCO_DL1 = Beta('B_WINTER_WALKING_NCO_DL1', 0, -10, 10, 1, 'B_WINTER_WALKING_NCO_DL1')
        B_WINTER_WALKING_CO1_DL0 = Beta('B_WINTER_WALKING_CO1_DL0', 0, -10, 10, 1, 'B_WINTER_WALKING_CO1_DL0')
        B_WINTER_WALKING_CO1_DL1 = Beta('B_WINTER_WALKING_CO1_DL1', 0, -10, 10, 1, 'B_WINTER_WALKING_CO1_DL1')
        B_WINTER_WALKING_CO2_DL0 = Beta('B_WINTER_WALKING_CO2_DL0', 0, -10, 10, 1, 'B_WINTER_WALKING_CO2_DL0')
        B_WINTER_WALKING_CO2_DL1 = Beta('B_WINTER_WALKING_CO2_DL1', 0, -10, 10, 1, 'B_WINTER_WALKING_CO2_DL1')

        co0 = DefineVariable('co0', self.car_ownership==0, self.database)
        co1 = DefineVariable('co1', self.car_ownership==1, self.database)
        co2 = DefineVariable('co2', self.car_ownership==2, self.database)
        self.weekday = DefineVariable('self.weekday', self.day_of_week<6, self.database)
        self.saturday = DefineVariable('self.saturday', self.day_of_week==6, self.database)
        self.child = DefineVariable('self.child', self.age<11.5, self.database)
        self.cadult = DefineVariable('self.cadult', (self.age>11.5) and (self.age<31.5), self.database)
        self.adult = DefineVariable('self.adult', (self.age>31.5) and (self.age<66.5), self.database)
        self.winter = DefineVariable('self.winter', (self.travel_month<3) or (self.travel_month==12), self.database)
        #ampeak = DefineVariable('ampeak', start_time_linear<9.5 and start_time_linear>=6.5)
        self.pmpeak = DefineVariable('self.pmpeak', (self.start_time_linear<19.5) and (self.start_time_linear>=16.5), self.database)
        self.interpeak = DefineVariable('self.interpeak', (self.start_time_linear<16.5) and (self.start_time_linear>=9.5), self.database)
        self.distance_km = DefineVariable('self.distance_km', self.distance/1000, self.database)
        self.logdistance = DefineVariable('self.logdistance', log(self.distance), self.database)
        dl0 = DefineVariable('dl0', self.driving_license==0, self.database)
        dl1 = DefineVariable('dl1', self.driving_license==1, self.database)
        #drive_cost = DefineVariable('drive_cost', self.cost_driving_total*(car_ownership>0))
        
        # Utility functions

        # For numerical reasons, it is good practice to scale the data to
        # that the values of the parameters are around 1.0.
        # A previous estimation with the unscaled data has generated
        # parameters around -0.01 for both cost and time. Therefore, time and
        # cost are multipled my 0.01.

        V1 = (((ASC_WALKING_NCO_DL0 * dl0 + ASC_WALKING_NCO_DL1 * dl1) * co0 + (
                    ASC_WALKING_CO1_DL0 * dl0 + ASC_WALKING_CO1_DL1 * dl1) * co1 + (
                           ASC_WALKING_CO2_DL0 * dl0 + ASC_WALKING_CO2_DL1 * dl1) * co2) +
              ((B_TIME_WALKING_NCO_DL0 * dl0 + B_TIME_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_TIME_WALKING_CO1_DL0 * dl0 + B_TIME_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_TIME_WALKING_CO2_DL0 * dl0 + B_TIME_WALKING_CO2_DL1 * dl1) * co2) * self.dur_walking +
              ((B_PURPOSE_B_WALKING_NCO_DL0 * dl0 + B_PURPOSE_B_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_B_WALKING_CO1_DL0 * dl0 + B_PURPOSE_B_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_B_WALKING_CO2_DL0 * dl0 + B_PURPOSE_B_WALKING_CO2_DL1 * dl1) * co2) * self.purpose_B +
              ((B_PURPOSE_HBW_WALKING_NCO_DL0 * dl0 + B_PURPOSE_HBW_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBW_WALKING_CO1_DL0 * dl0 + B_PURPOSE_HBW_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBW_WALKING_CO2_DL0 * dl0 + B_PURPOSE_HBW_WALKING_CO2_DL1 * dl1) * co2) * self.purpose_HBW +
              ((B_PURPOSE_HBE_WALKING_NCO_DL0 * dl0 + B_PURPOSE_HBE_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBE_WALKING_CO1_DL0 * dl0 + B_PURPOSE_HBE_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBE_WALKING_CO2_DL0 * dl0 + B_PURPOSE_HBE_WALKING_CO2_DL1 * dl1) * co2) * self.purpose_HBE +
              ((B_PURPOSE_HBO_WALKING_NCO_DL0 * dl0 + B_PURPOSE_HBO_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBO_WALKING_CO1_DL0 * dl0 + B_PURPOSE_HBO_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBO_WALKING_CO2_DL0 * dl0 + B_PURPOSE_HBO_WALKING_CO2_DL1 * dl1) * co2) * self.purpose_HBO +
              # ((B_CO1_WALKING_NCO_DL0*dl0 + B_CO1_WALKING_NCO_DL1*dl1)*co0 + (B_CO1_WALKING_CO1_DL0*dl0 + B_CO1_WALKING_CO1_DL1*dl1)*co1 + (B_CO1_WALKING_CO2_DL0*dl0 + B_CO1_WALKING_CO2_DL1*dl1)*co2) * co1 +
              # ((B_CO2_WALKING_NCO_DL0*dl0 + B_CO2_WALKING_NCO_DL1*dl1)*co0 + (B_CO2_WALKING_CO1_DL0*dl0 + B_CO2_WALKING_CO1_DL1*dl1)*co1 + (B_CO2_WALKING_CO2_DL0*dl0 + B_CO2_WALKING_CO2_DL1*dl1)*co2) * co2 +
              ((B_FEMALE_WALKING_NCO_DL0 * dl0 + B_FEMALE_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_FEMALE_WALKING_CO1_DL0 * dl0 + B_FEMALE_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_FEMALE_WALKING_CO2_DL0 * dl0 + B_FEMALE_WALKING_CO2_DL1 * dl1) * co2) * self.female +
              ((B_WINTER_WALKING_NCO_DL0 * dl0 + B_WINTER_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_WINTER_WALKING_CO1_DL0 * dl0 + B_WINTER_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_WINTER_WALKING_CO2_DL0 * dl0 + B_WINTER_WALKING_CO2_DL1 * dl1) * co2) * self.winter +
              ((B_CHILD_WALKING_NCO_DL0 * dl0 + B_CHILD_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_CHILD_WALKING_CO1_DL0 * dl0 + B_CHILD_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_CHILD_WALKING_CO2_DL0 * dl0 + B_CHILD_WALKING_CO2_DL1 * dl1) * co2) * self.child +
              ((B_CADULT_WALKING_NCO_DL0 * dl0 + B_CADULT_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_CADULT_WALKING_CO1_DL0 * dl0 + B_CADULT_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_CADULT_WALKING_CO2_DL0 * dl0 + B_CADULT_WALKING_CO2_DL1 * dl1) * co2) * self.cadult +
              ((B_ADULT_WALKING_NCO_DL0 * dl0 + B_ADULT_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_ADULT_WALKING_CO1_DL0 * dl0 + B_ADULT_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_ADULT_WALKING_CO2_DL0 * dl0 + B_ADULT_WALKING_CO2_DL1 * dl1) * co2) * self.adult +
              ((B_WEEKDAY_WALKING_NCO_DL0 * dl0 + B_WEEKDAY_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_WEEKDAY_WALKING_CO1_DL0 * dl0 + B_WEEKDAY_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_WEEKDAY_WALKING_CO2_DL0 * dl0 + B_WEEKDAY_WALKING_CO2_DL1 * dl1) * co2) * self.weekday +
              ((B_SATURDAY_WALKING_NCO_DL0 * dl0 + B_SATURDAY_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_SATURDAY_WALKING_CO1_DL0 * dl0 + B_SATURDAY_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_SATURDAY_WALKING_CO2_DL0 * dl0 + B_SATURDAY_WALKING_CO2_DL1 * dl1) * co2) * self.saturday +
              # ((B_AM_PEAK_WALKING_NCO_DL0*dl0 + B_AM_PEAK_WALKING_NCO_DL1*dl1)*co0 + (B_AM_PEAK_WALKING_CO1_DL0*dl0 + B_AM_PEAK_WALKING_CO1_DL1*dl1)*co1 + (B_AM_PEAK_WALKING_CO2_DL0*dl0 + B_AM_PEAK_WALKING_CO2_DL1*dl1)*co2) * ampeak +
              ((B_INTER_PEAK_WALKING_NCO_DL0 * dl0 + B_INTER_PEAK_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_INTER_PEAK_WALKING_CO1_DL0 * dl0 + B_INTER_PEAK_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_INTER_PEAK_WALKING_CO2_DL0 * dl0 + B_INTER_PEAK_WALKING_CO2_DL1 * dl1) * co2) * self.interpeak +
              ((B_PM_PEAK_WALKING_NCO_DL0 * dl0 + B_PM_PEAK_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_PM_PEAK_WALKING_CO1_DL0 * dl0 + B_PM_PEAK_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_PM_PEAK_WALKING_CO2_DL0 * dl0 + B_PM_PEAK_WALKING_CO2_DL1 * dl1) * co2) * self.pmpeak +
              ((B_DISTANCE_WALKING_NCO_DL0 * dl0 + B_DISTANCE_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_DISTANCE_WALKING_CO1_DL0 * dl0 + B_DISTANCE_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_DISTANCE_WALKING_CO2_DL0 * dl0 + B_DISTANCE_WALKING_CO2_DL1 * dl1) * co2) * self.distance_km +
              ((B_LOGDISTANCE_WALKING_NCO_DL0 * dl0 + B_LOGDISTANCE_WALKING_NCO_DL1 * dl1) * co0 + (
                          B_LOGDISTANCE_WALKING_CO1_DL0 * dl0 + B_LOGDISTANCE_WALKING_CO1_DL1 * dl1) * co1 + (
                           B_LOGDISTANCE_WALKING_CO2_DL0 * dl0 + B_LOGDISTANCE_WALKING_CO2_DL1 * dl1) * co2) * self.logdistance
              )

        V2 = (((ASC_CYCLING_NCO_DL0 * dl0 + ASC_CYCLING_NCO_DL1 * dl1) * co0 + (
                    ASC_CYCLING_CO1_DL0 * dl0 + ASC_CYCLING_CO1_DL1 * dl1) * co1 + (
                           ASC_CYCLING_CO2_DL0 * dl0 + ASC_CYCLING_CO2_DL1 * dl1) * co2) +
              ((B_TIME_CYCLING_NCO_DL0 * dl0 + B_TIME_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_TIME_CYCLING_CO1_DL0 * dl0 + B_TIME_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_TIME_CYCLING_CO2_DL0 * dl0 + B_TIME_CYCLING_CO2_DL1 * dl1) * co2) * self.dur_cycling +
              ((B_PURPOSE_B_CYCLING_NCO_DL0 * dl0 + B_PURPOSE_B_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_B_CYCLING_CO1_DL0 * dl0 + B_PURPOSE_B_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_B_CYCLING_CO2_DL0 * dl0 + B_PURPOSE_B_CYCLING_CO2_DL1 * dl1) * co2) * self.purpose_B +
              ((B_PURPOSE_HBW_CYCLING_NCO_DL0 * dl0 + B_PURPOSE_HBW_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBW_CYCLING_CO1_DL0 * dl0 + B_PURPOSE_HBW_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBW_CYCLING_CO2_DL0 * dl0 + B_PURPOSE_HBW_CYCLING_CO2_DL1 * dl1) * co2) * self.purpose_HBW +
              # ((B_PURPOSE_HBE_CYCLING_NCO_DL0*dl0 + B_PURPOSE_HBE_CYCLING_NCO_DL1*dl1)*co0 + (B_PURPOSE_HBE_CYCLING_CO1_DL0*dl0 + B_PURPOSE_HBE_CYCLING_CO1_DL1*dl1)*co1 + (B_PURPOSE_HBE_CYCLING_CO2_DL0*dl0 + B_PURPOSE_HBE_CYCLING_CO2_DL1*dl1)*co2) * self.purpose_HBE +
              ((B_PURPOSE_HBO_CYCLING_NCO_DL0 * dl0 + B_PURPOSE_HBO_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBO_CYCLING_CO1_DL0 * dl0 + B_PURPOSE_HBO_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBO_CYCLING_CO2_DL0 * dl0 + B_PURPOSE_HBO_CYCLING_CO2_DL1 * dl1) * co2) * self.purpose_HBO +
              # ((B_CO_CYCLING_NCO_DL0*dl0 + B_CO_CYCLING_NCO_DL1*dl1)*co0 + (B_CO_CYCLING_CO1_DL0*dl0 + B_CO_CYCLING_CO1_DL1*dl1)*co1 + (B_CO_CYCLING_CO2_DL0*dl0 + B_CO_CYCLING_CO2_DL1*dl1)*co2) * co1 +
              # ((B_CO_CYCLING_NCO_DL0*dl0 + B_CO_CYCLING_NCO_DL1*dl1)*co0 + (B_CO_CYCLING_CO1_DL0*dl0 + B_CO_CYCLING_CO1_DL1*dl1)*co1 + (B_CO_CYCLING_CO2_DL0*dl0 + B_CO_CYCLING_CO2_DL1*dl1)*co2) * co2 +
              ((B_FEMALE_CYCLING_NCO_DL0 * dl0 + B_FEMALE_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_FEMALE_CYCLING_CO1_DL0 * dl0 + B_FEMALE_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_FEMALE_CYCLING_CO2_DL0 * dl0 + B_FEMALE_CYCLING_CO2_DL1 * dl1) * co2) * self.female +
              ((B_WINTER_CYCLING_NCO_DL0 * dl0 + B_WINTER_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_WINTER_CYCLING_CO1_DL0 * dl0 + B_WINTER_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_WINTER_CYCLING_CO2_DL0 * dl0 + B_WINTER_CYCLING_CO2_DL1 * dl1) * co2) * self.winter +
              ((B_CHILD_CYCLING_NCO_DL0 * dl0 + B_CHILD_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_CHILD_CYCLING_CO1_DL0 * dl0 + B_CHILD_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_CHILD_CYCLING_CO2_DL0 * dl0 + B_CHILD_CYCLING_CO2_DL1 * dl1) * co2) * self.child +
              ((B_CADULT_CYCLING_NCO_DL0 * dl0 + B_CADULT_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_CADULT_CYCLING_CO1_DL0 * dl0 + B_CADULT_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_CADULT_CYCLING_CO2_DL0 * dl0 + B_CADULT_CYCLING_CO2_DL1 * dl1) * co2) * self.cadult +
              ((B_ADULT_CYCLING_NCO_DL0 * dl0 + B_ADULT_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_ADULT_CYCLING_CO1_DL0 * dl0 + B_ADULT_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_ADULT_CYCLING_CO2_DL0 * dl0 + B_ADULT_CYCLING_CO2_DL1 * dl1) * co2) * self.adult +
              # ((B_WEEKDAY_CYCLING_NCO_DL0*dl0 + B_WEEKDAY_CYCLING_NCO_DL1*dl1)*co0 + (B_WEEKDAY_CYCLING_CO1_DL0*dl0 + B_WEEKDAY_CYCLING_CO1_DL1*dl1)*co1 + (B_WEEKDAY_CYCLING_CO2_DL0*dl0 + B_WEEKDAY_CYCLING_CO2_DL1*dl1)*co2) * self.weekday +
              ((B_SATURDAY_CYCLING_NCO_DL0 * dl0 + B_SATURDAY_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_SATURDAY_CYCLING_CO1_DL0 * dl0 + B_SATURDAY_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_SATURDAY_CYCLING_CO2_DL0 * dl0 + B_SATURDAY_CYCLING_CO2_DL1 * dl1) * co2) * self.saturday +
              # ((B_AM_PEAK_CYCLING_NCO_DL0*dl0 + B_AM_PEAK_CYCLING_NCO_DL1*dl1)*co0 + (B_AM_PEAK_CYCLING_CO1_DL0*dl0 + B_AM_PEAK_CYCLING_CO1_DL1*dl1)*co1 + (B_AM_PEAK_CYCLING_CO2_DL0*dl0 + B_AM_PEAK_CYCLING_CO2_DL1*dl1)*co2) * ampeak +
              ((B_INTER_PEAK_CYCLING_NCO_DL0 * dl0 + B_INTER_PEAK_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_INTER_PEAK_CYCLING_CO1_DL0 * dl0 + B_INTER_PEAK_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_INTER_PEAK_CYCLING_CO2_DL0 * dl0 + B_INTER_PEAK_CYCLING_CO2_DL1 * dl1) * co2) * self.interpeak +
              ((B_PM_PEAK_CYCLING_NCO_DL0 * dl0 + B_PM_PEAK_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_PM_PEAK_CYCLING_CO1_DL0 * dl0 + B_PM_PEAK_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_PM_PEAK_CYCLING_CO2_DL0 * dl0 + B_PM_PEAK_CYCLING_CO2_DL1 * dl1) * co2) * self.pmpeak +
              ((B_DISTANCE_CYCLING_NCO_DL0 * dl0 + B_DISTANCE_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_DISTANCE_CYCLING_CO1_DL0 * dl0 + B_DISTANCE_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_DISTANCE_CYCLING_CO2_DL0 * dl0 + B_DISTANCE_CYCLING_CO2_DL1 * dl1) * co2) * self.distance_km +
              ((B_LOGDISTANCE_CYCLING_NCO_DL0 * dl0 + B_LOGDISTANCE_CYCLING_NCO_DL1 * dl1) * co0 + (
                          B_LOGDISTANCE_CYCLING_CO1_DL0 * dl0 + B_LOGDISTANCE_CYCLING_CO1_DL1 * dl1) * co1 + (
                           B_LOGDISTANCE_CYCLING_CO2_DL0 * dl0 + B_LOGDISTANCE_CYCLING_CO2_DL1 * dl1) * co2) * self.logdistance
              )

        V3 = (((ASC_TRANSIT_NCO_DL0 * dl0 + ASC_TRANSIT_NCO_DL1 * dl1) * co0 + (
                    ASC_TRANSIT_CO1_DL0 * dl0 + ASC_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           ASC_TRANSIT_CO2_DL0 * dl0 + ASC_TRANSIT_CO2_DL1 * dl1) * co2) +
              ((B_COST_TRANSIT_NCO_DL0 * dl0 + B_COST_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_COST_TRANSIT_CO1_DL0 * dl0 + B_COST_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_COST_TRANSIT_CO2_DL0 * dl0 + B_COST_TRANSIT_CO2_DL1 * dl1) * co2) * self.cost_transit +
              ((B_TIME_ACCESS_NCO_DL0 * dl0 + B_TIME_ACCESS_NCO_DL1 * dl1) * co0 + (
                          B_TIME_ACCESS_CO1_DL0 * dl0 + B_TIME_ACCESS_CO1_DL1 * dl1) * co1 + (
                           B_TIME_ACCESS_CO2_DL0 * dl0 + B_TIME_ACCESS_CO2_DL1 * dl1) * co2) * self.dur_access +
              ((B_TIME_RAIL_NCO_DL0 * dl0 + B_TIME_RAIL_NCO_DL1 * dl1) * co0 + (
                          B_TIME_RAIL_CO1_DL0 * dl0 + B_TIME_RAIL_CO1_DL1 * dl1) * co1 + (
                           B_TIME_RAIL_CO2_DL0 * dl0 + B_TIME_RAIL_CO2_DL1 * dl1) * co2) * self.dur_pt_rail +
              ((B_TIME_BUS_NCO_DL0 * dl0 + B_TIME_BUS_NCO_DL1 * dl1) * co0 + (
                          B_TIME_BUS_CO1_DL0 * dl0 + B_TIME_BUS_CO1_DL1 * dl1) * co1 + (
                           B_TIME_BUS_CO2_DL0 * dl0 + B_TIME_BUS_CO2_DL1 * dl1) * co2) * self.dur_pt_bus +
              ((B_TIME_INT_WAIT_NCO_DL0 * dl0 + B_TIME_INT_WAIT_NCO_DL1 * dl1) * co0 + (
                          B_TIME_INT_WAIT_CO1_DL0 * dl0 + B_TIME_INT_WAIT_CO1_DL1 * dl1) * co1 + (
                           B_TIME_INT_WAIT_CO2_DL0 * dl0 + B_TIME_INT_WAIT_CO2_DL1 * dl1) * co2) * self.dur_interchange_waiting +
              ((B_TIME_INT_WALK_NCO_DL0 * dl0 + B_TIME_INT_WALK_NCO_DL1 * dl1) * co0 + (
                          B_TIME_INT_WALK_CO1_DL0 * dl0 + B_TIME_INT_WALK_CO1_DL1 * dl1) * co1 + (
                           B_TIME_INT_WALK_CO2_DL0 * dl0 + B_TIME_INT_WALK_CO2_DL1 * dl1) * co2) * self.dur_interchange_walking +
              ((B_PURPOSE_B_TRANSIT_NCO_DL0 * dl0 + B_PURPOSE_B_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_B_TRANSIT_CO1_DL0 * dl0 + B_PURPOSE_B_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_B_TRANSIT_CO2_DL0 * dl0 + B_PURPOSE_B_TRANSIT_CO2_DL1 * dl1) * co2) * self.purpose_B +
              ((B_PURPOSE_HBW_TRANSIT_NCO_DL0 * dl0 + B_PURPOSE_HBW_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBW_TRANSIT_CO1_DL0 * dl0 + B_PURPOSE_HBW_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBW_TRANSIT_CO2_DL0 * dl0 + B_PURPOSE_HBW_TRANSIT_CO2_DL1 * dl1) * co2) * self.purpose_HBW +
              ((B_PURPOSE_HBE_TRANSIT_NCO_DL0 * dl0 + B_PURPOSE_HBE_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBE_TRANSIT_CO1_DL0 * dl0 + B_PURPOSE_HBE_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBE_TRANSIT_CO2_DL0 * dl0 + B_PURPOSE_HBE_TRANSIT_CO2_DL1 * dl1) * co2) * self.purpose_HBE +
              ((B_PURPOSE_HBO_TRANSIT_NCO_DL0 * dl0 + B_PURPOSE_HBO_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBO_TRANSIT_CO1_DL0 * dl0 + B_PURPOSE_HBO_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBO_TRANSIT_CO2_DL0 * dl0 + B_PURPOSE_HBO_TRANSIT_CO2_DL1 * dl1) * co2) * self.purpose_HBO +
              # ((B_CO1_TRANSIT_NCO_DL0*dl0 + B_CO1_TRANSIT_NCO_DL1*dl1)*co0 + (B_CO1_TRANSIT_CO1_DL0*dl0 + B_CO1_TRANSIT_CO1_DL1*dl1)*co1 + (B_CO1_TRANSIT_CO2_DL0*dl0 + B_CO1_TRANSIT_CO2_DL1*dl1)*co2) * co1 +
              # ((B_CO2_TRANSIT_NCO_DL0*dl0 + B_CO2_TRANSIT_NCO_DL1*dl1)*co0 + (B_CO2_TRANSIT_CO1_DL0*dl0 + B_CO2_TRANSIT_CO1_DL1*dl1)*co1 + (B_CO2_TRANSIT_CO2_DL0*dl0 + B_CO2_TRANSIT_CO2_DL1*dl1)*co2) * co2 +
              ((B_FEMALE_TRANSIT_NCO_DL0 * dl0 + B_FEMALE_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_FEMALE_TRANSIT_CO1_DL0 * dl0 + B_FEMALE_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_FEMALE_TRANSIT_CO2_DL0 * dl0 + B_FEMALE_TRANSIT_CO2_DL1 * dl1) * co2) * self.female +
              # ((B_WINTER_TRANSIT_NCO_DL0*dl0 + B_WINTER_TRANSIT_NCO_DL1*dl1)*co0 + (B_WINTER_TRANSIT_CO1_DL0*dl0 + B_WINTER_TRANSIT_CO1_DL1*dl1)*co1 + (B_WINTER_TRANSIT_CO2_DL0*dl0 + B_WINTER_TRANSIT_CO2_DL1*dl1)*co2) * self.winter +
              ((B_CHILD_TRANSIT_NCO_DL0 * dl0 + B_CHILD_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_CHILD_TRANSIT_CO1_DL0 * dl0 + B_CHILD_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_CHILD_TRANSIT_CO2_DL0 * dl0 + B_CHILD_TRANSIT_CO2_DL1 * dl1) * co2) * self.child +
              ((B_CADULT_TRANSIT_NCO_DL0 * dl0 + B_CADULT_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_CADULT_TRANSIT_CO1_DL0 * dl0 + B_CADULT_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_CADULT_TRANSIT_CO2_DL0 * dl0 + B_CADULT_TRANSIT_CO2_DL1 * dl1) * co2) * self.cadult +
              ((B_ADULT_TRANSIT_NCO_DL0 * dl0 + B_ADULT_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_ADULT_TRANSIT_CO1_DL0 * dl0 + B_ADULT_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_ADULT_TRANSIT_CO2_DL0 * dl0 + B_ADULT_TRANSIT_CO2_DL1 * dl1) * co2) * self.adult +
              ((B_WEEKDAY_TRANSIT_NCO_DL0 * dl0 + B_WEEKDAY_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_WEEKDAY_TRANSIT_CO1_DL0 * dl0 + B_WEEKDAY_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_WEEKDAY_TRANSIT_CO2_DL0 * dl0 + B_WEEKDAY_TRANSIT_CO2_DL1 * dl1) * co2) * self.weekday +
              ((B_SATURDAY_TRANSIT_NCO_DL0 * dl0 + B_SATURDAY_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_SATURDAY_TRANSIT_CO1_DL0 * dl0 + B_SATURDAY_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_SATURDAY_TRANSIT_CO2_DL0 * dl0 + B_SATURDAY_TRANSIT_CO2_DL1 * dl1) * co2) * self.saturday +
              # ((B_AM_PEAK_TRANSIT_NCO_DL0*dl0 + B_AM_PEAK_TRANSIT_NCO_DL1*dl1)*co0 + (B_AM_PEAK_TRANSIT_CO1_DL0*dl0 + B_AM_PEAK_TRANSIT_CO1_DL1*dl1)*co1 + (B_AM_PEAK_TRANSIT_CO2_DL0*dl0 + B_AM_PEAK_TRANSIT_CO2_DL1*dl1)*co2) * ampeak +
              # ((B_INTER_PEAK_TRANSIT_NCO_DL0*dl0 + B_INTER_PEAK_TRANSIT_NCO_DL1*dl1)*co0 + (B_INTER_PEAK_TRANSIT_CO1_DL0*dl0 + B_INTER_PEAK_TRANSIT_CO1_DL1*dl1)*co1 + (B_INTER_PEAK_TRANSIT_CO2_DL0*dl0 + B_INTER_PEAK_TRANSIT_CO2_DL1*dl1)*co2) * self.interpeak +
              ((B_PM_PEAK_TRANSIT_NCO_DL0 * dl0 + B_PM_PEAK_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_PM_PEAK_TRANSIT_CO1_DL0 * dl0 + B_PM_PEAK_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_PM_PEAK_TRANSIT_CO2_DL0 * dl0 + B_PM_PEAK_TRANSIT_CO2_DL1 * dl1) * co2) * self.pmpeak +
              ((B_DISTANCE_TRANSIT_NCO_DL0 * dl0 + B_DISTANCE_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_DISTANCE_TRANSIT_CO1_DL0 * dl0 + B_DISTANCE_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_DISTANCE_TRANSIT_CO2_DL0 * dl0 + B_DISTANCE_TRANSIT_CO2_DL1 * dl1) * co2) * self.distance_km +
              ((B_LOGDISTANCE_TRANSIT_NCO_DL0 * dl0 + B_LOGDISTANCE_TRANSIT_NCO_DL1 * dl1) * co0 + (
                          B_LOGDISTANCE_TRANSIT_CO1_DL0 * dl0 + B_LOGDISTANCE_TRANSIT_CO1_DL1 * dl1) * co1 + (
                           B_LOGDISTANCE_TRANSIT_CO2_DL0 * dl0 + B_LOGDISTANCE_TRANSIT_CO2_DL1 * dl1) * co2) * self.logdistance
              )

        V4 = (((ASC_DRIVING_NCO_DL0 * dl0 + ASC_DRIVING_NCO_DL1 * dl1) * co0 + (
                    ASC_DRIVING_CO1_DL0 * dl0 + ASC_DRIVING_CO1_DL1 * dl1) * co1 + (
                           ASC_DRIVING_CO2_DL0 * dl0 + ASC_DRIVING_CO2_DL1 * dl1) * co2) +
              ((B_TIME_DRIVING_NCO_DL0 * dl0 + B_TIME_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_TIME_DRIVING_CO1_DL0 * dl0 + B_TIME_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_TIME_DRIVING_CO2_DL0 * dl0 + B_TIME_DRIVING_CO2_DL1 * dl1) * co2) * self.dur_driving +
              ((B_COST_CON_NCO_DL0 * dl0 + B_COST_CON_NCO_DL1 * dl1) * co0 + (
                          B_COST_CON_CO1_DL0 * dl0 + B_COST_CON_CO1_DL1 * dl1) * co1 + (
                           B_COST_CON_CO2_DL0 * dl0 + B_COST_CON_CO2_DL1 * dl1) * co2) * self.con_charge +
              ((B_COST_FUEL_NCO_DL0 * dl0 + B_COST_FUEL_NCO_DL1 * dl1) * co0 + (
                          B_COST_FUEL_CO1_DL0 * dl0 + B_COST_FUEL_CO1_DL1 * dl1) * co1 + (
                           B_COST_FUEL_CO2_DL0 * dl0 + B_COST_FUEL_CO2_DL1 * dl1) * co2) * self.cost_driving +
              ((B_TRAFFIC_NCO_DL0 * dl0 + B_TRAFFIC_NCO_DL1 * dl1) * co0 + (
                          B_TRAFFIC_CO1_DL0 * dl0 + B_TRAFFIC_CO1_DL1 * dl1) * co1 + (
                           B_TRAFFIC_CO2_DL0 * dl0 + B_TRAFFIC_CO2_DL1 * dl1) * co2) * self.traffic_percent +
              ((B_PURPOSE_B_DRIVING_NCO_DL0 * dl0 + B_PURPOSE_B_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_B_DRIVING_CO1_DL0 * dl0 + B_PURPOSE_B_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_B_DRIVING_CO2_DL0 * dl0 + B_PURPOSE_B_DRIVING_CO2_DL1 * dl1) * co2) * self.purpose_B +
              ((B_PURPOSE_HBW_DRIVING_NCO_DL0 * dl0 + B_PURPOSE_HBW_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBW_DRIVING_CO1_DL0 * dl0 + B_PURPOSE_HBW_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBW_DRIVING_CO2_DL0 * dl0 + B_PURPOSE_HBW_DRIVING_CO2_DL1 * dl1) * co2) * self.purpose_HBW +
              ((B_PURPOSE_HBE_DRIVING_NCO_DL0 * dl0 + B_PURPOSE_HBE_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBE_DRIVING_CO1_DL0 * dl0 + B_PURPOSE_HBE_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBE_DRIVING_CO2_DL0 * dl0 + B_PURPOSE_HBE_DRIVING_CO2_DL1 * dl1) * co2) * self.purpose_HBE +
              ((B_PURPOSE_HBO_DRIVING_NCO_DL0 * dl0 + B_PURPOSE_HBO_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_PURPOSE_HBO_DRIVING_CO1_DL0 * dl0 + B_PURPOSE_HBO_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_PURPOSE_HBO_DRIVING_CO2_DL0 * dl0 + B_PURPOSE_HBO_DRIVING_CO2_DL1 * dl1) * co2) * self.purpose_HBO +
              # ((B_CO1_DRIVING_NCO_DL0*dl0 + B_CO1_DRIVING_NCO_DL1*dl1)*co0 + (B_CO1_DRIVING_CO1_DL0*dl0 + B_CO1_DRIVING_CO1_DL1*dl1)*co1 + (B_CO1_DRIVING_CO2_DL0*dl0 + B_CO1_DRIVING_CO2_DL1*dl1)*co2) * co1 +
              # ((B_CO2_DRIVING_NCO_DL0*dl0 + B_CO2_DRIVING_NCO_DL1*dl1)*co0 + (B_CO2_DRIVING_CO1_DL0*dl0 + B_CO2_DRIVING_CO1_DL1*dl1)*co1 + (B_CO2_DRIVING_CO2_DL0*dl0 + B_CO2_DRIVING_CO2_DL1*dl1)*co2) * co2 +
              ((B_FEMALE_DRIVING_NCO_DL0 * dl0 + B_FEMALE_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_FEMALE_DRIVING_CO1_DL0 * dl0 + B_FEMALE_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_FEMALE_DRIVING_CO2_DL0 * dl0 + B_FEMALE_DRIVING_CO2_DL1 * dl1) * co2) * self.female +
              ((B_WINTER_DRIVING_NCO_DL0 * dl0 + B_WINTER_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_WINTER_DRIVING_CO1_DL0 * dl0 + B_WINTER_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_WINTER_DRIVING_CO2_DL0 * dl0 + B_WINTER_DRIVING_CO2_DL1 * dl1) * co2) * self.winter +
              ((B_CHILD_DRIVING_NCO_DL0 * dl0 + B_CHILD_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_CHILD_DRIVING_CO1_DL0 * dl0 + B_CHILD_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_CHILD_DRIVING_CO2_DL0 * dl0 + B_CHILD_DRIVING_CO2_DL1 * dl1) * co2) * self.child +
              ((B_CADULT_DRIVING_NCO_DL0 * dl0 + B_CADULT_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_CADULT_DRIVING_CO1_DL0 * dl0 + B_CADULT_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_CADULT_DRIVING_CO2_DL0 * dl0 + B_CADULT_DRIVING_CO2_DL1 * dl1) * co2) * self.cadult +
              ((B_ADULT_DRIVING_NCO_DL0 * dl0 + B_ADULT_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_ADULT_DRIVING_CO1_DL0 * dl0 + B_ADULT_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_ADULT_DRIVING_CO2_DL0 * dl0 + B_ADULT_DRIVING_CO2_DL1 * dl1) * co2) * self.adult +
              ((B_WEEKDAY_DRIVING_NCO_DL0 * dl0 + B_WEEKDAY_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_WEEKDAY_DRIVING_CO1_DL0 * dl0 + B_WEEKDAY_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_WEEKDAY_DRIVING_CO2_DL0 * dl0 + B_WEEKDAY_DRIVING_CO2_DL1 * dl1) * co2) * self.weekday +
              # ((B_SATURDAY_DRIVING_NCO_DL0*dl0 + B_SATURDAY_DRIVING_NCO_DL1*dl1)*co0 + (B_SATURDAY_DRIVING_CO1_DL0*dl0 + B_SATURDAY_DRIVING_CO1_DL1*dl1)*co1 + (B_SATURDAY_DRIVING_CO2_DL0*dl0 + B_SATURDAY_DRIVING_CO2_DL1*dl1)*co2) * self.saturday +
              # ((B_AM_PEAK_DRIVING_NCO_DL0*dl0 + B_AM_PEAK_DRIVING_NCO_DL1*dl1)*co0 + (B_AM_PEAK_DRIVING_CO1_DL0*dl0 + B_AM_PEAK_DRIVING_CO1_DL1*dl1)*co1 + (B_AM_PEAK_DRIVING_CO2_DL0*dl0 + B_AM_PEAK_DRIVING_CO2_DL1*dl1)*co2) * ampeak +
              ((B_INTER_PEAK_DRIVING_NCO_DL0 * dl0 + B_INTER_PEAK_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_INTER_PEAK_DRIVING_CO1_DL0 * dl0 + B_INTER_PEAK_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_INTER_PEAK_DRIVING_CO2_DL0 * dl0 + B_INTER_PEAK_DRIVING_CO2_DL1 * dl1) * co2) * self.interpeak +
              ((B_PM_PEAK_DRIVING_NCO_DL0 * dl0 + B_PM_PEAK_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_PM_PEAK_DRIVING_CO1_DL0 * dl0 + B_PM_PEAK_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_PM_PEAK_DRIVING_CO2_DL0 * dl0 + B_PM_PEAK_DRIVING_CO2_DL1 * dl1) * co2) * self.pmpeak +
              ((B_DISTANCE_DRIVING_NCO_DL0 * dl0 + B_DISTANCE_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_DISTANCE_DRIVING_CO1_DL0 * dl0 + B_DISTANCE_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_DISTANCE_DRIVING_CO2_DL0 * dl0 + B_DISTANCE_DRIVING_CO2_DL1 * dl1) * co2) * self.distance_km +
              ((B_LOGDISTANCE_DRIVING_NCO_DL0 * dl0 + B_LOGDISTANCE_DRIVING_NCO_DL1 * dl1) * co0 + (
                          B_LOGDISTANCE_DRIVING_CO1_DL0 * dl0 + B_LOGDISTANCE_DRIVING_CO1_DL1 * dl1) * co1 + (
                           B_LOGDISTANCE_DRIVING_CO2_DL0 * dl0 + B_LOGDISTANCE_DRIVING_CO2_DL1 * dl1) * co2) * self.logdistance
              )

        # Associate utility functions with the numbering of alternatives
        V = {1: V1,
             2: V2,
             3: V3,
             4: V4}

        av = {1: 1,
              2: 1,
              3: 1,
              4: 1}

        # The choice model is a logit, with availability conditions
        logprob = bioLogLogit(V, av, self.tmode)

        self.biogeme = bio.BIOGEME(self.database, logprob)
        self.biogeme.modelName = "ComplexLondonTravelMNL"
        self.biogeme.generateHtml = False


        self.size_db = len(self.database.data)
        self.x0 = np.zeros(len(self.biogeme.betaInitValues))

    def optimize(self, algo, **kwargs):

        if 'biogeme' in kwargs.keys():
            raise ValueError('Please remove biogeme from the kwargs.')

        params = {'biogeme': self.biogeme,
                  'full_size': len(self.biogeme.database.data)}

        for k in kwargs.keys():
            params[k] = kwargs[k]

        self.algo = algo(self.biogeme.calculateLikelihood, self.x0, **params)

        return self.algo.solve(maximize=True)

