#!/bin/bash -l
#SBATCH --chdir /home/glederre/DCM_Opti/code/server/LPMC_DrivingCost_big
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 24
#SBATCH --mem 192000
#SBATCH --time=12:00:00

module load gcc/7.4.0 python/3.6.5
source ~/pybio/bin/activate
echo Starting optimization of LPMC_DrivingCost_big with LS-ABS and inv-bfgs at `date`
srun python -u LS-ABS_inv-bfgs.py
echo Finished at `date`

