sbatch LS_grad.run
sbatch LS-ABS_grad.run
sbatch LS_hess.run
sbatch TR_hess.run
sbatch LS-ABS_hess.run
sbatch TR-ABS_hess.run
sbatch LS_bfgs.run
sbatch TR_bfgs.run
sbatch LS-ABS_bfgs.run
sbatch TR-ABS_bfgs.run
sbatch LS-ABS_hybrid.run
sbatch TR-ABS_hybrid.run
