python LS-ABS_grad.py
python LS-ABS_hess.py
python TR-ABS_hess.py
python LS-ABS_bfgs.py
python TR-ABS_bfgs.py
python LS-ABS_bfgs-inv.py
python LS-ABS_hybrid.py
python TR-ABS_hybrid.py
python LS-ABS_hybrid-inv.py
python biogeme_bfgs_tol.py
